Repository alephium/alephium-frontend, pull requests merged in 2023-12, with the labels that each got.

#153 Fix iOS build
  apps/mobile-wallet/app.config.js
  apps/mobile-wallet/index.ts
  apps/mobile-wallet/ios/Alephium.xcodeproj/project.pbxproj
  apps/mobile-wallet/ios/Podfile
  apps/mobile-wallet/ios/Podfile.lock
  apps/mobile-wallet/ios/Podfile.properties.json
  apps/mobile-wallet/metro.config.js
  bun.lockb
  packages/shared/package.json
  packages/shared/test/numbers-test.ts
  packages/shared/test/wallet-test.ts
  turbo.json
Labels: 📱 MW, android, iOS

#152 Replace comma with full-stop in amount input
  .changeset/mean-knives-bake.md
  apps/mobile-wallet/src/screens/SendReceive/Send/AssetsScreen/AssetRow.tsx
  apps/mobile-wallet/src/utils/numbers.ts
Labels: 🖥 DW

#125 Register WC deep link schema, show toast message on success, update WC project ID
  .changeset/happy-ligers-swim.md
  .changeset/quiet-bats-obey.md
  apps/mobile-wallet/android/app/src/main/AndroidManifest.xml
  apps/mobile-wallet/app.config.js
  apps/mobile-wallet/ios/Alephium/Info.plist
  apps/mobile-wallet/src/contexts/walletConnect/WalletConnectContext.tsx
  apps/mobile-wallet/src/utils/addresses.ts
  apps/mobile-wallet/src/utils/layout.ts
Labels: 📱 MW

#148 Fix path to node_modules
  .changeset/flat-cooks-itch.md
  .changeset/funny-moles-smash.md
  .changeset/stale-toys-hunt.md
  apps/desktop-wallet/package.json
Labels: 🖥 DW, macOS

#162 Toast new layout + bit of drying up
  .changeset/serious-dots-crash.md
  apps/mobile-wallet/src/App.tsx
  apps/mobile-wallet/src/components/toasts/Toast.tsx
  apps/mobile-wallet/src/components/toasts/ToastAnchor.tsx
  apps/mobile-wallet/src/utils/layout.ts
Labels: 📱 MW

#173 Fix currency, scrollbars, password autofocus, user data path
  .changeset/brown-cougars-flash.md
  .changeset/honest-seals-explode.md
  apps/desktop-wallet/public/electron.js
  apps/desktop-wallet/src/components/SnackbarManager.tsx
  apps/desktop-wallet/src/pages/HomePage/UnlockPanel.tsx
  apps/desktop-wallet/src/pages/UnlockedWallet/AddressesPage/AddressGridRow.tsx
  apps/desktop-wallet/src/pages/UnlockedWallet/OverviewPage/AmountsOverviewPanel.tsx
Labels: 🖥 DW

#169 Improve desktop wallet auto-updater by considering rc versions
  .changeset/famous-garlics-appear.md
  .vscode/settings.json
  apps/desktop-wallet/public/electron.js
  apps/desktop-wallet/src/hooks/useLatestGitHubRelease.ts
Labels: 🖥 DW

#184 Allow searching by address public key in explorer
  .changeset/plenty-pugs-hope.md
  apps/explorer/src/components/SearchBar.tsx
  apps/explorer/src/utils/strings.ts
  apps/explorer/src/utils/util.test.ts
Labels: 🔎 XPLR

#195 Update web3 packages to 0.27.2
  bun.lockb
  package.json
Labels: 📱 MW, 🖥 DW

#201 Fix WC double init
  .changeset/tricky-snails-swim.md
  apps/mobile-wallet/src/contexts/walletConnect/WalletConnectContext.tsx
Labels: 📱 MW
