Repository alephium/alephium-frontend, pull requests merged in 2024-04, with the labels that each got.

#499 Fixes for DW NFTs PR
  apps/desktop-wallet/src/components/AddressBadge.tsx
  apps/desktop-wallet/src/components/DataList.tsx
  apps/desktop-wallet/src/components/Inputs/AddressSelect.tsx
  apps/desktop-wallet/src/modals/AddressDetailsModal.tsx
  apps/desktop-wallet/src/modals/ModalContainer.tsx
  apps/desktop-wallet/src/modals/SendModals/CheckAddressesBox.tsx
  apps/desktop-wallet/src/modals/TransactionDetailsModal.tsx
  apps/desktop-wallet/src/pages/UnlockedWallet/AddressesPage/AddressGridRow.tsx
  apps/desktop-wallet/src/pages/UnlockedWallet/OverviewPage/AssetsList.tsx
  apps/desktop-wallet/src/utils/misc.ts
Labels: 🖥 DW

#493 Improve NFT and TX display & use RTK Query to fetch collection data
  .changeset/dull-boats-burn.md
  .changeset/eleven-pugs-talk.md
  .changeset/tidy-lobsters-brake.md
  .changeset/two-crabs-raise.md
  apps/desktop-wallet/locales/bg-BG/translation.json
  apps/desktop-wallet/locales/de-DE/translation.json
  apps/desktop-wallet/locales/en-US/translation.json
  apps/desktop-wallet/locales/es-ES/translation.json
  apps/desktop-wallet/locales/fr-FR/translation.json
  apps/desktop-wallet/locales/id-ID/translation.json
  apps/desktop-wallet/locales/it-IT/translation.json
  apps/desktop-wallet/locales/pt-PT/translation.json
  apps/desktop-wallet/locales/ru-RU/translation.json
  apps/desktop-wallet/locales/tr-TR/translation.json
  apps/desktop-wallet/locales/vi-VN/translation.json
  apps/desktop-wallet/src/animations/index.ts
  apps/desktop-wallet/src/components/ActionLink.tsx
  apps/desktop-wallet/src/components/AddressBadge.tsx
  apps/desktop-wallet/src/components/AppHeader.tsx
  apps/desktop-wallet/src/components/AssetBadge.tsx
  apps/desktop-wallet/src/components/Badge.tsx
  apps/desktop-wallet/src/components/Card3D.tsx
  apps/desktop-wallet/src/components/DataList.tsx
  apps/desktop-wallet/src/components/ExpandableSection.tsx
  apps/desktop-wallet/src/components/FocusableContent.tsx
  apps/desktop-wallet/src/components/Inputs/AddressSelect.tsx
  apps/desktop-wallet/src/components/NFTCard.tsx
  apps/desktop-wallet/src/components/NFTThumbnail.tsx
  apps/desktop-wallet/src/components/Tooltip.tsx
  apps/desktop-wallet/src/components/TransactionalInfo.tsx
  apps/desktop-wallet/src/hooks/useThrottledGitHubApi.ts
  apps/desktop-wallet/src/modals/AddressDetailsModal.tsx
  apps/desktop-wallet/src/modals/ModalContainer.tsx
  apps/desktop-wallet/src/modals/NFTDetailsModal.tsx
  apps/desktop-wallet/src/modals/SendModals/CheckAddressesBox.tsx
  apps/desktop-wallet/src/modals/SideModal.tsx
  apps/desktop-wallet/src/modals/TransactionDetailsModal.tsx
  apps/desktop-wallet/src/pages/UnlockedWallet/AddressesPage/AddressGridRow.tsx
  apps/desktop-wallet/src/pages/UnlockedWallet/AddressesPage/OperationBox.tsx
  apps/desktop-wallet/src/pages/UnlockedWallet/OverviewPage/AssetsList.tsx
  apps/desktop-wallet/src/pages/UnlockedWallet/OverviewPage/index.tsx
  apps/desktop-wallet/src/pages/UnlockedWallet/TransfersPage/FiltersPanel.tsx
  apps/desktop-wallet/src/storage/store.ts
  apps/desktop-wallet/src/style/globalStyles.ts
  apps/desktop-wallet/src/style/themes.ts
  apps/desktop-wallet/src/utils/misc.ts
  apps/explorer/src/App.tsx
  apps/explorer/src/api/assets/assetsApi.ts
  packages/shared/src/api/baseQuery.ts
  packages/shared/src/api/index.ts
  packages/shared/src/api/nftsApi.ts
  packages/shared/src/constants.ts
  packages/shared/src/store/store.ts
Labels: 🖥 DW

#515 Fixes before 2.2.5 release & add mp4 NFT display
  .changeset/empty-poets-hide.md
  apps/desktop-wallet/locales/bg-BG/translation.json
  apps/desktop-wallet/locales/de-DE/translation.json
  apps/desktop-wallet/locales/en-US/translation.json
  apps/desktop-wallet/locales/es-ES/translation.json
  apps/desktop-wallet/locales/fr-FR/translation.json
  apps/desktop-wallet/locales/id-ID/translation.json
  apps/desktop-wallet/locales/it-IT/translation.json
  apps/desktop-wallet/locales/pt-PT/translation.json
  apps/desktop-wallet/locales/ru-RU/translation.json
  apps/desktop-wallet/locales/tr-TR/translation.json
  apps/desktop-wallet/locales/vi-VN/translation.json
  apps/desktop-wallet/package.json
  apps/desktop-wallet/src/components/AssetBadge.tsx
  apps/desktop-wallet/src/components/AssetLogo.tsx
  apps/desktop-wallet/src/components/Inputs/SelectOptionAsset.tsx
  apps/desktop-wallet/src/components/NFTCard.tsx
  apps/desktop-wallet/src/components/NFTThumbnail.tsx
  apps/desktop-wallet/src/components/TableCellAmount.tsx
  apps/desktop-wallet/src/components/TransactionalInfo.tsx
  apps/desktop-wallet/src/modals/NFTDetailsModal.tsx
  apps/desktop-wallet/src/modals/SendModals/AssetAmountsInput.tsx
  apps/desktop-wallet/src/modals/SendModals/CheckAmountsBox.tsx
  apps/desktop-wallet/src/modals/TransactionDetailsModal.tsx
  apps/desktop-wallet/src/modals/WalletConnect/WalletConnectSessionProposalModal.tsx
  apps/desktop-wallet/src/modals/WalletConnectModal.tsx
  apps/desktop-wallet/src/pages/UnlockedWallet/OverviewPage/AssetsList.tsx
  pnpm-lock.yaml
Labels: 🖥 DW

#534 Privacy manifest
  apps/mobile-wallet/CHANGELOG.md
  apps/mobile-wallet/android/app/build.gradle
  apps/mobile-wallet/app.config.js
  apps/mobile-wallet/ios/Alephium.xcodeproj/project.pbxproj
  apps/mobile-wallet/ios/Alephium/Info.plist
  apps/mobile-wallet/ios/Alephium/PrivacyInfo.xcprivacy
  apps/mobile-wallet/ios/Podfile.lock
  apps/mobile-wallet/package.json
  pnpm-lock.yaml
Labels: 📱 MW

#544 Secrets fixes
  apps/desktop-wallet/locales/en-US/translation.json
  apps/desktop-wallet/package.json
  apps/desktop-wallet/src/components/PasswordConfirmation.tsx
  apps/desktop-wallet/src/hooks/useAddressGeneration.tsx
  apps/desktop-wallet/src/hooks/useWalletLock.ts
  apps/desktop-wallet/src/modals/SettingsModal/WalletsSettingsSection.tsx
  apps/desktop-wallet/src/storage/addresses/addressesStorageUtils.ts
  apps/desktop-wallet/src/utils/migration.ts
  pnpm-lock.yaml
Labels: 🖥 DW

#549 Add AUD
  .changeset/brave-ears-approve.md
  .changeset/shy-ads-fry.md
  packages/shared/src/currencies.ts
  packages/shared/src/types/currencies.ts
Labels: 🤲 SHRD
