Repository alephium/alephium-frontend, pull requests merged in 2024-01, with the labels that each got.

#233 Fix AssetBadge decimals
  .changeset/cold-geese-bake.md
  apps/desktop-wallet/src/components/AssetBadge.tsx
Labels: 🖥 DW

#257 Add clear cache button in general settings
  .changeset/afraid-snakes-kneel.md
  apps/desktop-wallet/locales/bg-BG/translation.json
  apps/desktop-wallet/locales/de-DE/translation.json
  apps/desktop-wallet/locales/en-US/translation.json
  apps/desktop-wallet/locales/es-ES/translation.json
  apps/desktop-wallet/locales/fr-FR/translation.json
  apps/desktop-wallet/locales/id-ID/translation.json
  apps/desktop-wallet/locales/it-IT/translation.json
  apps/desktop-wallet/locales/pt-PT/translation.json
  apps/desktop-wallet/locales/ru-RU/translation.json
  apps/desktop-wallet/locales/tr-TR/translation.json
  apps/desktop-wallet/locales/vi-VN/translation.json
  apps/desktop-wallet/src/contexts/walletconnect.tsx
  apps/desktop-wallet/src/modals/SettingsModal/GeneralSettingsSection.tsx
  apps/desktop-wallet/src/storage/global/globalActions.ts
  apps/desktop-wallet/src/storage/global/snackbarSlice.ts
Labels: 🖥 DW

#259 Fix desktop wallet freeze
  .changeset/gold-ants-dream.md
  .changeset/tasty-goats-remember.md
  .changeset/tender-ghosts-smell.md
  apps/desktop-wallet/src/contexts/walletconnect.tsx
  apps/mobile-wallet/src/contexts/walletConnect/WalletConnectContext.tsx
Labels: WalletConnect, 🖥 DW

#256 Detect biometrics change and fallback to pin
  .changeset/old-baboons-drive.md
  .changeset/stupid-eagles-float.md
  apps/mobile-wallet/src/navigation/RootStackNavigation.tsx
  apps/mobile-wallet/src/persistent-storage/wallet.ts
  apps/mobile-wallet/src/screens/LoginWithPinScreen.tsx
Labels: 📱 MW

#261 Sign Windows binary with FIPS 140-2 compliant setup
  .github/workflows/release-desktop.yml
  .github/workflows/test.yml
  apps/desktop-wallet/.signWindows.js
  apps/desktop-wallet/package.json
  pnpm-lock.yaml
Labels: 🖥 DW, windows

#283 Sign messages through WalletConnect
  .changeset/lazy-suns-repeat.md
  .changeset/polite-melons-repeat.md
  .changeset/sixty-windows-draw.md
  apps/desktop-wallet/locales/bg-BG/translation.json
  apps/desktop-wallet/locales/de-DE/translation.json
  apps/desktop-wallet/locales/en-US/translation.json
  apps/desktop-wallet/locales/es-ES/translation.json
  apps/desktop-wallet/locales/fr-FR/translation.json
  apps/desktop-wallet/locales/id-ID/translation.json
  apps/desktop-wallet/locales/it-IT/translation.json
  apps/desktop-wallet/locales/pt-PT/translation.json
  apps/desktop-wallet/locales/ru-RU/translation.json
  apps/desktop-wallet/locales/tr-TR/translation.json
  apps/desktop-wallet/locales/vi-VN/translation.json
  apps/desktop-wallet/scripts/syncTranslationFiles.js
  apps/desktop-wallet/src/components/HistoricWorthChart.tsx
  apps/desktop-wallet/src/contexts/walletconnect.tsx
  apps/desktop-wallet/src/modals/WalletConnect/SignMessageModal.tsx
  apps/desktop-wallet/src/modals/WalletConnect/SignUnsignedTxModal.tsx
  apps/desktop-wallet/src/storage/addresses/addressesActions.ts
  apps/desktop-wallet/src/storage/assets/priceApiSlice.ts
  apps/desktop-wallet/src/storage/transactions/transactionsActions.ts
  apps/desktop-wallet/src/types/transactions.ts
  apps/desktop-wallet/src/utils/constants.ts
  apps/mobile-wallet/eas.json
  apps/mobile-wallet/ios/Podfile.lock
  apps/mobile-wallet/package.json
  apps/mobile-wallet/src/api/addresses.ts
  apps/mobile-wallet/src/components/HistoricWorthChart.tsx
  apps/mobile-wallet/src/components/QRCodeScannerModal.tsx
  apps/mobile-wallet/src/contexts/walletConnect/WalletConnectContext.tsx
  apps/mobile-wallet/src/contexts/walletConnect/WalletConnectSessionRequestModal.tsx
  apps/mobile-wallet/src/navigation/BackupMnemonicNavigation.tsx
  apps/mobile-wallet/src/navigation/RootStackNavigation.tsx
  apps/mobile-wallet/src/screens/BackupMnemonic/VerificationSuccessScreen.tsx
  apps/mobile-wallet/src/screens/BackupMnemonic/VerifyMnemonicScreen.tsx
  apps/mobile-wallet/src/screens/Dashboard/WalletConnectPairingsModal.tsx
  apps/mobile-wallet/src/store/assets/priceApiSlice.ts
  apps/mobile-wallet/src/types/transactions.ts
  apps/mobile-wallet/src/types/walletConnect.ts
  apps/mobile-wallet/src/utils/constants.ts
  packages/shared/lib/constants.ts
  packages/shared/lib/walletConnect.ts
  packages/shared/package.json
  pnpm-lock.yaml
  turbo.json
Labels: WalletConnect, 📱 MW, 🖥 DW, 🤲 SHRD

#293 Fix list of suggested words in import screen of desktop wallet
  .changeset/eighty-students-greet.md
  apps/desktop-wallet/package.json
  package.json
  patches/@yaireo__tagify@4.18.3.patch
  pnpm-lock.yaml
Labels: 🖥 DW

#284 Bump version of mobile wallet to 1.0.4
  .changeset/fresh-stingrays-drum.md
  .changeset/lazy-suns-repeat.md
  .changeset/long-steaks-drop.md
  .changeset/old-baboons-drive.md
  .changeset/pink-cars-scream.md
  .changeset/rude-mice-push.md
  .changeset/sixty-windows-draw.md
  .changeset/stupid-eagles-float.md
  .changeset/tender-ghosts-smell.md
  apps/mobile-wallet/CHANGELOG.md
  apps/mobile-wallet/android/app/build.gradle
  apps/mobile-wallet/app.config.js
  apps/mobile-wallet/ios/Alephium/Info.plist
  apps/mobile-wallet/package.json
  packages/shared/CHANGELOG.md
  packages/shared/package.json
Labels: 📱 MW

#295 Respond to WalletConnect while app in background
  apps/mobile-wallet/CHANGELOG.md
  apps/mobile-wallet/android/app/build.gradle
  apps/mobile-wallet/android/app/src/main/AndroidManifest.xml
  apps/mobile-wallet/app.config.js
  apps/mobile-wallet/ios/Alephium/Info.plist
  apps/mobile-wallet/ios/Podfile.lock
  apps/mobile-wallet/package.json
  apps/mobile-wallet/src/contexts/walletConnect/WalletConnectContext.tsx
  apps/mobile-wallet/src/navigation/BackupMnemonicNavigation.tsx
  apps/mobile-wallet/src/navigation/RootStackNavigation.tsx
  apps/mobile-wallet/src/screens/BackupMnemonic/BackupIntroScreen.tsx
  apps/mobile-wallet/src/screens/new-wallet/ImportWalletSeedScreen.tsx
  pnpm-lock.yaml
Labels: WalletConnect, 📱 MW

#296 Bug fixes & Bump desktop wallet version to 2.2.1
  .changeset/afraid-snakes-kneel.md
  .changeset/cold-geese-bake.md
  .changeset/eighty-students-greet.md
  .changeset/gold-ants-dream.md
  .changeset/polite-melons-repeat.md
  .changeset/tasty-goats-remember.md
  apps/desktop-wallet/CHANGELOG.md
  apps/desktop-wallet/package.json
  apps/desktop-wallet/src/components/Inputs/TextAreaTags.tsx
  apps/desktop-wallet/src/hooks/useLatestGitHubRelease.ts
  apps/desktop-wallet/src/modals/SettingsModal/index.tsx
  apps/desktop-wallet/src/utils/links.ts
  package.json
  patches/@yaireo__tagify@4.18.3.patch
  pnpm-lock.yaml
Labels: 🖥 DW

#321 Hotfix
  apps/desktop-wallet/CHANGELOG.md
  apps/desktop-wallet/package.json
  apps/desktop-wallet/src/App.tsx
  apps/desktop-wallet/src/components/AddressBadge.tsx
  apps/desktop-wallet/src/components/AddressRow.tsx
  apps/desktop-wallet/src/components/Amount.tsx
  apps/desktop-wallet/src/components/AppHeader.tsx
  apps/desktop-wallet/src/components/Badge.tsx
  apps/desktop-wallet/src/components/Button.tsx
  apps/desktop-wallet/src/components/Buttons/ShortcutButtons.tsx
  apps/desktop-wallet/src/components/DefaultAddressSwitch.tsx
  apps/desktop-wallet/src/components/DeltaPercentage.tsx
  apps/desktop-wallet/src/components/ExpandableSection.tsx
  apps/desktop-wallet/src/components/IOList.tsx
  apps/desktop-wallet/src/components/Inputs/AddressSelect.tsx
  apps/desktop-wallet/src/components/Inputs/CompactToggle.tsx
  apps/desktop-wallet/src/components/Inputs/Input.tsx
  apps/desktop-wallet/src/components/Inputs/MultiSelect.tsx
  apps/desktop-wallet/src/components/Inputs/Select.tsx
  apps/desktop-wallet/src/components/Inputs/SelectOptionAddress.tsx
  apps/desktop-wallet/src/components/Inputs/WalletPassphrase.tsx
  apps/desktop-wallet/src/components/Inputs/index.tsx
  apps/desktop-wallet/src/components/NavItem.tsx
  apps/desktop-wallet/src/components/NetworkSwitch.tsx
  apps/desktop-wallet/src/components/PageComponents/PageContainers.tsx
  apps/desktop-wallet/src/components/PageComponents/SideBar.tsx
  apps/desktop-wallet/src/components/Popup.tsx
  apps/desktop-wallet/src/components/TabBar.tsx
  apps/desktop-wallet/src/components/Table.tsx
  apps/desktop-wallet/src/components/TableTabBar.tsx
  apps/desktop-wallet/src/components/TransactionList.tsx
  apps/desktop-wallet/src/components/TransactionalInfo.tsx
  apps/desktop-wallet/src/index.tsx
  apps/desktop-wallet/src/modals/AddressDetailsModal.tsx
  apps/desktop-wallet/src/modals/CenteredModal.tsx
  apps/desktop-wallet/src/modals/NewAddressModal.tsx
  apps/desktop-wallet/src/modals/NotificationsModal.tsx
  apps/desktop-wallet/src/modals/SendModals/AddressInputs.tsx
  apps/desktop-wallet/src/modals/SendModals/CheckAddressesBox.tsx
  apps/desktop-wallet/src/modals/SettingsModal/DevToolsSettingsSection.tsx
  apps/desktop-wallet/src/modals/SettingsModal/EditWalletNameModal.tsx
  apps/desktop-wallet/src/modals/SettingsModal/GeneralSettingsSection.tsx
  apps/desktop-wallet/src/modals/SettingsModal/NetworkSettingsSection.tsx
  apps/desktop-wallet/src/modals/SettingsModal/WalletsSettingsSection.tsx
  apps/desktop-wallet/src/modals/SettingsModal/index.tsx
  apps/desktop-wallet/src/modals/SideModal.tsx
  apps/desktop-wallet/src/modals/TransactionDetailsModal.tsx
  apps/desktop-wallet/src/modals/WalletConnectModal.tsx
  apps/desktop-wallet/src/pages/UnlockedWallet/AddressesPage/AddressGridRow.tsx
  apps/desktop-wallet/src/pages/UnlockedWallet/AddressesPage/ContactsTabContent.tsx
  apps/desktop-wallet/src/pages/UnlockedWallet/AddressesPage/TabContent.tsx
  apps/desktop-wallet/src/pages/UnlockedWallet/OverviewPage/AmountsOverviewPanel.tsx
  apps/desktop-wallet/src/pages/UnlockedWallet/OverviewPage/index.tsx
  apps/desktop-wallet/src/pages/UnlockedWallet/TransfersPage/index.tsx
  apps/desktop-wallet/src/pages/UnlockedWallet/UnlockedWalletLayout.tsx
Labels: 🖥 DW
