Repository alephium/alephium-frontend, pull requests merged in 2024-03, with the labels that each got.

#405 Display fiat worth of each token in mobile wallet and sort assets of both wallets based on worth
  .changeset/brave-onions-hear.md
  .changeset/quick-worms-brush.md
  .changeset/thick-zebras-float.md
  apps/desktop-wallet/src/pages/UnlockedWallet/OverviewPage/AssetsList.tsx
  apps/desktop-wallet/src/storage/addresses/addressesSelectors.ts
  apps/mobile-wallet/src/components/TokenListItem.tsx
  apps/mobile-wallet/src/store/addressesSlice.ts
  packages/shared/src/assets.ts
  packages/shared/src/index.ts
  packages/shared/src/types/assets.ts
  turbo.json
Labels: 📱 MW, 🖥 DW, 🤲 SHRD

#423 Fix all fetches
  apps/desktop-wallet/src/components/AnnouncementBanner.tsx
  apps/desktop-wallet/src/hooks/useLatestGitHubRelease.ts
  apps/desktop-wallet/src/storage/global/globalActions.ts
  apps/mobile-wallet/src/api/price.ts
Labels: 🖥 DW

#446 Handle WC request to sign unsigned tx in mobile wallet
  .changeset/chilly-peaches-flow.md
  .changeset/wet-pandas-confess.md
  apps/desktop-wallet/locales/bg-BG/translation.json
  apps/desktop-wallet/locales/de-DE/translation.json
  apps/desktop-wallet/locales/en-US/translation.json
  apps/desktop-wallet/locales/es-ES/translation.json
  apps/desktop-wallet/locales/fr-FR/translation.json
  apps/desktop-wallet/locales/id-ID/translation.json
  apps/desktop-wallet/locales/it-IT/translation.json
  apps/desktop-wallet/locales/pt-PT/translation.json
  apps/desktop-wallet/locales/ru-RU/translation.json
  apps/desktop-wallet/locales/tr-TR/translation.json
  apps/desktop-wallet/locales/vi-VN/translation.json
  apps/desktop-wallet/src/contexts/walletconnect.tsx
  apps/desktop-wallet/src/modals/WalletConnect/SignMessageModal.tsx
  apps/desktop-wallet/src/modals/WalletConnect/SignUnsignedTxModal.tsx
  apps/desktop-wallet/src/storage/global/snackbarSlice.ts
  apps/desktop-wallet/src/storage/transactions/transactionsActions.ts
  apps/mobile-wallet/src/components/Row.tsx
  apps/mobile-wallet/src/contexts/walletConnect/WalletConnectContext.tsx
  apps/mobile-wallet/src/contexts/walletConnect/WalletConnectSessionRequestModal.tsx
  apps/mobile-wallet/src/types/transactions.ts
  apps/mobile-wallet/src/types/walletConnect.ts
  packages/shared/src/constants.ts
Labels: 📱 MW

#454 More export options, NFT details fixes, better loading and order by token worth
  .changeset/chatty-rivers-reply.md
  apps/explorer/locales/en-US/translation.json
  apps/explorer/locales/fr-FR/translation.json
  apps/explorer/locales/id-ID/translation.json
  apps/explorer/src/pages/AddressInfoPage/AssetList.tsx
  apps/explorer/src/pages/AddressInfoPage/ExportAddressTXsModal.tsx
  apps/explorer/src/pages/AddressInfoPage/NFTDetailsModal.tsx
  apps/explorer/src/pages/AddressInfoPage/NFTList.tsx
  apps/explorer/src/pages/AddressInfoPage/TokenList.tsx
  apps/explorer/src/types/assets.ts
Labels: 🔎 XPLR

#451 [1.0.8] Fix bottom modal padding
  apps/mobile-wallet/src/components/AddressFlatListScreen.tsx
  apps/mobile-wallet/src/components/layout/BottomModal.tsx
  apps/mobile-wallet/src/components/layout/ModalContent.tsx
Labels: 📱 MW

#467 [1.0.8] Public keys screen
  .changeset/thirty-olives-cross.md
  apps/mobile-wallet/ios/Alephium.xcodeproj/project.pbxproj
  apps/mobile-wallet/ios/Podfile.lock
  apps/mobile-wallet/src/components/AddressBadge.tsx
  apps/mobile-wallet/src/components/AddressFlatListScreen.tsx
  apps/mobile-wallet/src/components/Row.tsx
  apps/mobile-wallet/src/components/headers/BaseHeader.tsx
  apps/mobile-wallet/src/components/layout/FlatListScreen.tsx
  apps/mobile-wallet/src/components/layout/ScreenIntro.tsx
  apps/mobile-wallet/src/components/layout/ScreenTitle.tsx
  apps/mobile-wallet/src/components/layout/ScrollScreen.tsx
  apps/mobile-wallet/src/navigation/RootStackNavigation.tsx
  apps/mobile-wallet/src/navigation/rootStackRoutes.ts
  apps/mobile-wallet/src/screens/AddressDiscoveryScreen.tsx
  apps/mobile-wallet/src/screens/BackupMnemonic/VerifyMnemonicScreen.tsx
  apps/mobile-wallet/src/screens/PublicKeysScreen.tsx
  apps/mobile-wallet/src/screens/SendReceive/Receive/AddressScreen.tsx
  apps/mobile-wallet/src/screens/SendReceive/Receive/QRCodeScreen.tsx
  apps/mobile-wallet/src/screens/SendReceive/Send/AssetsScreen/index.tsx
  apps/mobile-wallet/src/screens/SendReceive/Send/DestinationScreen.tsx
  apps/mobile-wallet/src/screens/SendReceive/Send/OriginScreen.tsx
  apps/mobile-wallet/src/screens/SendReceive/Send/VerifyScreen.tsx
  apps/mobile-wallet/src/screens/Settings/SettingsScreen.tsx
  apps/mobile-wallet/src/screens/new-wallet/DecryptScannedMnemonicScreen.tsx
  apps/mobile-wallet/src/screens/new-wallet/ImportWalletSeedScreen.tsx
  apps/mobile-wallet/src/screens/new-wallet/SelectImportMethodScreen.tsx
  apps/mobile-wallet/src/style/globalStyle.ts
  apps/mobile-wallet/src/utils/addresses.ts
Labels: 📱 MW

#469 Simplify app metadata
  apps/desktop-wallet/src/components/AnnouncementBanner.tsx
  apps/desktop-wallet/src/hooks/useThrottledGitHubApi.ts
  apps/desktop-wallet/src/utils/app-data.ts
Labels: 🖥 DW

#455 [1.0.8] Fix image loading
  .changeset/seven-cheetahs-beam.md
  .changeset/slow-countries-juggle.md
  apps/mobile-wallet/src/App.tsx
  apps/mobile-wallet/src/api/addresses.ts
  apps/mobile-wallet/src/components/AddressBox.tsx
  apps/mobile-wallet/src/components/AddressesTokensList.tsx
  apps/mobile-wallet/src/components/BalanceSummary.tsx
  apps/mobile-wallet/src/components/NFTThumbnail.tsx
  apps/mobile-wallet/src/components/NFTsGrid.tsx
  apps/mobile-wallet/src/components/RefreshSpinner.tsx
  apps/mobile-wallet/src/components/layout/TransactionsFlatList.tsx
  apps/mobile-wallet/src/contexts/walletConnect/WalletConnectContext.tsx
  apps/mobile-wallet/src/navigation/RootStackNavigation.tsx
  apps/mobile-wallet/src/screens/Dashboard/DashboardScreen.tsx
  apps/mobile-wallet/src/screens/Dashboard/InitialDataLoader.tsx
  apps/mobile-wallet/src/screens/Dashboard/useLoader.ts
  apps/mobile-wallet/src/screens/LoginWithPinScreen.tsx
  apps/mobile-wallet/src/screens/TransactionModal.tsx
  apps/mobile-wallet/src/store/addressesSlice.ts
  apps/mobile-wallet/src/store/loadersSlice.ts
  apps/mobile-wallet/src/store/store.ts
Labels: 📱 MW

#472 Fix tokens logos un update unverified label
  apps/desktop-wallet/src/components/AssetLogo.tsx
  apps/mobile-wallet/src/components/AssetLogo.tsx
  apps/mobile-wallet/src/components/TokenListItem.tsx
Labels: 📱 MW, 🖥 DW

#477 Simplify WC button rendering logic
  apps/mobile-wallet/src/screens/Dashboard/WalletConnectHeaderButton.tsx
Labels: WalletConnect, 📱 MW
