Repository alephium/alephium-frontend, pull requests merged in 2024-11, with the labels that each got.

#948 Fix ALPH on devnet
  .changeset/small-timers-roll.md
  apps/desktop-wallet/src/api/apiDataHooks/utils/useFetchFtList.ts
Labels: 🖥 DW

#956 Devnet faucet in DW
  .changeset/twelve-pants-relax.md
  apps/desktop-wallet/locales/de-DE/translation.json
  apps/desktop-wallet/locales/el-GR/translation.json
  apps/desktop-wallet/locales/en-US/translation.json
  apps/desktop-wallet/locales/fr-FR/translation.json
  apps/desktop-wallet/locales/id-ID/translation.json
  apps/desktop-wallet/locales/it-IT/translation.json
  apps/desktop-wallet/locales/pt-PT/translation.json
  apps/desktop-wallet/locales/ru-RU/translation.json
  apps/desktop-wallet/locales/vi-VN/translation.json
  apps/desktop-wallet/locales/zh-CN/translation.json
  apps/desktop-wallet/src/features/send/sentTransactions/sentTransactionsSlice.ts
  apps/desktop-wallet/src/features/transactionsDisplay/transactionDetailsModal/PendingSentAddressBadge.tsx
  apps/desktop-wallet/src/modals/SettingsModal/DevToolsSettingsSection.tsx
  apps/desktop-wallet/src/storage/global/globalActions.ts
  apps/desktop-wallet/src/storage/global/globalSlice.ts
  apps/desktop-wallet/src/storage/global/snackbarSlice.ts
Labels: 🖥 DW

#944 Increase appHangTimeoutInterval to 5s
  apps/mobile-wallet/setupErrorHandling.ts
Labels: 📱 MW

#973 Fix sentry
  apps/mobile-wallet/setupErrorHandling.ts
  apps/mobile-wallet/src/analytics.tsx
  apps/mobile-wallet/src/persistent-storage/wallet.ts
  apps/mobile-wallet/src/screens/BackupMnemonic/VerifyMnemonicScreen.tsx
  apps/mobile-wallet/src/screens/LandingScreen.tsx
  apps/mobile-wallet/src/screens/Settings/MnemonicModal.tsx
  apps/mobile-wallet/src/store/addressDiscoverySlice.ts
Labels: 📱 MW

#976 Fix tx deltas mw
  .changeset/clean-trains-attack.md
  .changeset/dirty-mirrors-remain.md
  .changeset/eleven-pianos-repeat.md
  apps/desktop-wallet/src/features/send/SendModal.tsx
  apps/desktop-wallet/src/features/send/sentTransactions/SentTransactionSnackbarPopup.tsx
  apps/explorer/src/pages/TransactionInfoPage.tsx
  apps/explorer/src/utils/transactions.ts
  apps/mobile-wallet/src/components/TransactionListItem.tsx
  apps/mobile-wallet/src/screens/TransactionModal.tsx
Labels: 📱 MW, 🖥 DW

#978 Improve asset selection
  .changeset/clean-spiders-roll.md
  .changeset/moody-crabs-add.md
  apps/desktop-wallet/src/api/apiDataHooks/wallet/useFetchWalletNftsSearchStrings.ts
  apps/desktop-wallet/src/components/Inputs/Select.tsx
  apps/desktop-wallet/src/features/send/AddressInputs.tsx
  apps/desktop-wallet/src/features/send/TokensAmountInputs.tsx
  apps/desktop-wallet/src/modals/AddressSelectModal.tsx
Labels: 🖥 DW

#979 Hide bytecode field behind an expandable section
  .changeset/afraid-feet-impress.md
  apps/mobile-wallet/src/components/ExpandableRow.tsx
  apps/mobile-wallet/src/contexts/walletConnect/WalletConnectSessionRequestModal.tsx
Labels: 📱 MW

#988 Data loading indication
  .changeset/strong-countries-grow.md
  apps/desktop-wallet/locales/en-US/translation.json
  apps/desktop-wallet/src/api/apiDataHooks/apiDataHooksUtils.ts
  apps/desktop-wallet/src/api/apiDataHooks/wallet/useFetchWalletBalancesAlph.ts
  apps/desktop-wallet/src/api/apiDataHooks/wallet/useFetchWalletBalancesTokens.ts
  apps/desktop-wallet/src/api/apiDataHooks/wallet/useFetchWalletWorth.ts
  apps/desktop-wallet/src/components/Amount.tsx
  apps/desktop-wallet/src/components/WorthOverview.tsx
  apps/desktop-wallet/src/pages/UnlockedWallet/OverviewPage/WalletWorth.tsx
Labels: 🖥 DW

#993 Fix display of ALPH amounts
  .changeset/dirty-candles-flash.md
  apps/desktop-wallet/src/api/apiDataHooks/address/useFetchAddressBalances.ts
  apps/desktop-wallet/src/api/apiDataHooks/address/useFetchAddressSingleTokenBalances.ts
  apps/desktop-wallet/src/api/apiDataHooks/wallet/useFetchWalletBalances.ts
  apps/desktop-wallet/src/api/apiDataHooks/wallet/useFetchWalletSingleTokenBalances.ts
  apps/desktop-wallet/src/api/apiDataHooks/wallet/useFetchWalletTokensByType.ts
Labels: 🖥 DW

#997 Disable send btn when wallet empty
  .changeset/great-gorillas-itch.md
  apps/desktop-wallet/locales/en-US/translation.json
  apps/desktop-wallet/src/components/Buttons/ShortcutButtons.tsx
Labels: 🖥 DW

#1008 Fix WalletConnect connection removal
  .changeset/silent-wombats-impress.md
  apps/desktop-wallet/src/style/globalStyles.ts
  apps/mobile-wallet/src/contexts/walletConnect/WalletConnectContext.tsx
Labels: WalletConnect, 📱 MW
