Repository alephium/alephium-frontend, pull requests merged in 2024-06, with the labels that each got.

#603 Fix WC transfer request
  .changeset/six-hornets-hide.md
  apps/desktop-wallet/src/contexts/walletconnect.tsx
Labels: WalletConnect, 🖥 DW

#607 Use un-versioned node & explorer endpoints
  .changeset/thin-buckets-vanish.md
  .changeset/violet-goats-promise.md
  apps/desktop-wallet/src/tests/migration.test.ts
  apps/desktop-wallet/src/utils/migration.ts
  apps/mobile-wallet/ios/Podfile.lock
  apps/mobile-wallet/src/persistent-storage/wallet.ts
  apps/mobile-wallet/src/utils/migration.ts
  packages/shared/src/network.ts
Labels: 📱 MW, 🖥 DW, 🤲 SHRD

#606 Show fungible tokens with broken metadata in the correct tab
  .changeset/beige-frogs-rhyme.md
  apps/explorer/src/api/assets/assetsApi.ts
  apps/explorer/src/components/Amount.tsx
Labels: 🔎 XPLR

#637 Add privacy policy in mobile wallet
  apps/mobile-wallet/src/screens/Settings/SettingsScreen.tsx
Labels: 📱 MW

#653 Add explorer to Crowdin
  .github/workflows/translations-sync.yml
  crowdin.yml
Labels: 🔎 XPLR

#667 Show avg. block time in seconds
  .changeset/purple-cougars-change.md
  apps/explorer/src/pages/HomePage/HomePage.tsx
Labels: 🔎 XPLR

#689 Fix spacing of NFTs in bottom modals & authentication errors
  .github/actions/setup-monorepo/action.yml
  apps/desktop-wallet/package.json
  apps/desktop-wallet/turbo.json
  apps/explorer/package.json
  apps/explorer/turbo.json
  apps/mobile-wallet/eas.json
  apps/mobile-wallet/src/components/DeprecatedAuthenticationModal.tsx
  apps/mobile-wallet/src/components/NFTThumbnail.tsx
  apps/mobile-wallet/src/components/layout/BottomModal.tsx
  apps/mobile-wallet/src/features/auto-lock/useAutoLock.tsx
  apps/mobile-wallet/src/features/localization/i18next.d.ts
  apps/mobile-wallet/src/hooks/useBiometrics.ts
  apps/mobile-wallet/src/navigation/RootStackNavigation.tsx
  apps/mobile-wallet/src/persistent-storage/settings.ts
  apps/mobile-wallet/src/persistent-storage/wallet.ts
  apps/mobile-wallet/src/screens/LandingScreen.tsx
  apps/mobile-wallet/src/store/appSlice.ts
  apps/mobile-wallet/src/store/settingsSlice.ts
  apps/mobile-wallet/src/utils/navigation.ts
  package.json
  patches/framer-motion@10.17.12.patch
  pnpm-lock.yaml
Labels: 📱 MW

#699 Bump all projects
  .changeset/curvy-ghosts-love.md
  .changeset/fuzzy-ladybugs-yawn.md
  .changeset/little-rocks-draw.md
  .changeset/modern-jokes-boil.md
  .changeset/odd-readers-watch.md
  .changeset/olive-bears-happen.md
  .changeset/popular-clouds-joke.md
  .changeset/red-timers-rhyme.md
  .changeset/rude-glasses-perform.md
  .changeset/sixty-kids-complain.md
  .changeset/soft-weeks-kick.md
  .changeset/unlucky-pears-remember.md
  apps/desktop-wallet/CHANGELOG.md
  apps/desktop-wallet/package.json
  apps/explorer/CHANGELOG.md
  apps/explorer/package.json
  apps/mobile-wallet/CHANGELOG.md
  apps/mobile-wallet/android/app/build.gradle
  apps/mobile-wallet/app.config.js
  apps/mobile-wallet/ios/Alephium/Info.plist
  apps/mobile-wallet/package.json
Labels: 📱 MW, 🖥 DW, 🔎 XPLR
