Repository alephium/alephium-frontend, pull requests merged in 2024-08, with the labels that each got.

#754 Remove type casting when updating address data
  apps/desktop-wallet/src/App.tsx
  apps/desktop-wallet/src/api/addresses.ts
  apps/desktop-wallet/src/components/TransactionList.tsx
  apps/desktop-wallet/src/storage/addresses/addressesActions.ts
  apps/desktop-wallet/src/storage/addresses/addressesSlice.ts
  apps/desktop-wallet/src/storage/global/snackbarSlice.ts
  apps/desktop-wallet/src/storage/store.ts
  apps/desktop-wallet/src/storage/transactions/pendingTransactionsPersistentStorage.ts
  apps/desktop-wallet/src/storage/transactions/pendingTransactionsSlice.ts
  apps/desktop-wallet/src/storage/transactions/transactionsActions.ts
  apps/desktop-wallet/src/storage/transactions/transactionsStorageUtils.ts
  apps/desktop-wallet/src/types/addresses.ts
  apps/desktop-wallet/src/utils/migration.ts
  package.json
  pnpm-lock.yaml
Labels: 🖥 DW

#765 Fix keyboard content overlap
  .changeset/cold-carpets-kneel.md
  apps/mobile-wallet/src/components/layout/Screen.tsx
  apps/mobile-wallet/src/screens/SendReceive/Send/AssetsScreen/AssetRow.tsx
  apps/mobile-wallet/src/screens/SendReceive/Send/AssetsScreen/index.tsx
Labels: 📱 MW

#770 Fix being stuck in empty Landing screen
  .changeset/silver-falcons-guess.md
  apps/mobile-wallet/src/features/auto-lock/useAutoLock.tsx
  apps/mobile-wallet/src/screens/LandingScreen.tsx
Labels: 📱 MW

#751 Banxa
  apps/mobile-wallet/locales/en-US/translation.json
  apps/mobile-wallet/src/components/AddressBadge.tsx
  apps/mobile-wallet/src/components/AddressCard.tsx
  apps/mobile-wallet/src/components/AddressesTokensList.tsx
  apps/mobile-wallet/src/components/BalanceSummary.tsx
  apps/mobile-wallet/src/components/DeprecatedAuthenticationModal.tsx
  apps/mobile-wallet/src/components/TabBar.tsx
  apps/mobile-wallet/src/components/buttons/Button.tsx
  apps/mobile-wallet/src/components/headers/StackHeader.tsx
  apps/mobile-wallet/src/components/layout/BottomModal.tsx
  apps/mobile-wallet/src/components/layout/ScrollScreen.tsx
  apps/mobile-wallet/src/components/text/CenteredInstructions.tsx
  apps/mobile-wallet/src/components/text/LinkToWeb.tsx
  apps/mobile-wallet/src/features/buy/BuyModal.tsx
  apps/mobile-wallet/src/screens/AddressDiscoveryScreen.tsx
  apps/mobile-wallet/src/screens/Addresses/AddressesScreen.tsx
  apps/mobile-wallet/src/screens/ContactListScreenBase.tsx
  apps/mobile-wallet/src/screens/Dashboard/DashboardScreen.tsx
  apps/mobile-wallet/src/screens/Dashboard/HeaderButtons.tsx
  apps/mobile-wallet/src/screens/Dashboard/WalletConnectPairingsModal.tsx
  apps/mobile-wallet/src/screens/LandingScreen.tsx
  apps/mobile-wallet/src/screens/SendReceive/Receive/QRCodeScreen.tsx
  apps/mobile-wallet/src/screens/SendReceive/Send/DestinationScreen.tsx
  apps/mobile-wallet/src/screens/SendReceive/Send/VerifyScreen.tsx
  apps/mobile-wallet/src/screens/Settings/SettingsScreen.tsx
  apps/mobile-wallet/src/screens/Settings/WalletDeleteModal.tsx
  apps/mobile-wallet/src/screens/TransactionModal.tsx
  apps/mobile-wallet/src/store/addressesSlice.ts
  apps/mobile-wallet/src/style/globalStyle.ts
  pnpm-lock.yaml
Labels: 📱 MW

#786 Fix stuck in black screen
  .changeset/wise-jars-add.md
  apps/mobile-wallet/src/features/auto-lock/useAutoLock.tsx
  apps/mobile-wallet/src/navigation/RootStackNavigation.tsx
  apps/mobile-wallet/src/screens/LandingScreen.tsx
  patches/react-native-background-actions@3.0.1.patch
  pnpm-lock.yaml
Labels: 📱 MW

#792 Update WalletConnect deps to 2.15.1 and web3 to 1.5.1
  apps/desktop-wallet/package.json
  apps/explorer/package.json
  apps/mobile-wallet/package.json
  packages/keyring/package.json
  packages/shared/package.json
  pnpm-lock.yaml
Labels: WalletConnect, 📱 MW, 🖥 DW

#784 Use Tanstack data to determine if addresses have assets
  apps/desktop-wallet/src/components/Inputs/AddressSelect.tsx
  apps/desktop-wallet/src/components/Inputs/SelectOptionAddress.tsx
  apps/desktop-wallet/src/features/addressFiltering/addressFilteringHooks.tsx
  apps/desktop-wallet/src/modals/AddressSelectModal.tsx
  apps/desktop-wallet/src/modals/AddressSweepModal.tsx
  apps/desktop-wallet/src/modals/ReceiveModal.tsx
  apps/desktop-wallet/src/modals/SendModals/AddressInputs.tsx
  apps/desktop-wallet/src/modals/SendModals/CallContract/AddressesTxModalContent.tsx
  apps/desktop-wallet/src/modals/SendModals/DeployContract/AddressesTxModalContent.tsx
  apps/desktop-wallet/src/modals/SendModals/Transfer/AddressesTxModalContent.tsx
  apps/desktop-wallet/src/modals/WalletConnect/WalletConnectSessionProposalModal.tsx
  apps/desktop-wallet/src/pages/UnlockedWallet/AddressesPage/AddressesTabContent.tsx
  apps/desktop-wallet/src/pages/UnlockedWallet/TransfersPage/FiltersPanel.tsx
  apps/desktop-wallet/src/storage/addresses/addressesSelectors.ts
  apps/desktop-wallet/src/utils/addresses.ts
Labels: 🖥 DW

#776 Banxa UI tweaks / first steps into app redesign
  .changeset/eleven-dodos-jog.md
  .changeset/poor-olives-cheer.md
  apps/mobile-wallet/ios/Podfile.lock
  apps/mobile-wallet/locales/en-US/translation.json
  apps/mobile-wallet/package.json
  apps/mobile-wallet/src/components/AddressesTokensList.tsx
  apps/mobile-wallet/src/components/BalanceSummary.tsx
  apps/mobile-wallet/src/components/ListItem.tsx
  apps/mobile-wallet/src/components/NFTsGrid.tsx
  apps/mobile-wallet/src/components/WalletSwitchButton.tsx
  apps/mobile-wallet/src/components/footers/FooterMenu.tsx
  apps/mobile-wallet/src/components/footers/FooterMenuItem.tsx
  apps/mobile-wallet/src/components/headers/BaseHeader.tsx
  apps/mobile-wallet/src/components/headers/ProgressHeader.tsx
  apps/mobile-wallet/src/components/layout/BottomBarScrollScreen.tsx
  apps/mobile-wallet/src/components/layout/ScrollScreen.tsx
  apps/mobile-wallet/src/features/buy/BuyModal.tsx
  apps/mobile-wallet/src/navigation/InWalletNavigation.tsx
  apps/mobile-wallet/src/screens/ActivityScreen.tsx
  apps/mobile-wallet/src/screens/Dashboard/AnimatedCirclesBackground.tsx
  apps/mobile-wallet/src/screens/Dashboard/DashboardScreen.tsx
  apps/mobile-wallet/src/screens/Dashboard/HeaderButtons.tsx
  apps/mobile-wallet/src/screens/NFTs/NFTListScreen.tsx
  apps/mobile-wallet/src/screens/SendReceive/Receive/QRCodeScreen.tsx
  apps/mobile-wallet/src/screens/SendReceive/Send/AssetsScreen/index.tsx
  apps/mobile-wallet/src/screens/SendReceive/Send/VerifyScreen.tsx
  pnpm-lock.yaml
Labels: 📱 MW

#789 Use Tanstack data to display assets badge lists
  apps/desktop-wallet/locales/en-US/translation.json
  apps/desktop-wallet/locales/fr-FR/translation.json
  apps/desktop-wallet/locales/id-ID/translation.json
  apps/desktop-wallet/locales/it-IT/translation.json
  apps/desktop-wallet/locales/pt-PT/translation.json
  apps/desktop-wallet/locales/ru-RU/translation.json
  apps/desktop-wallet/locales/vi-VN/translation.json
  apps/desktop-wallet/src/api/addressesListedFungibleTokensDataHooks.ts
  apps/desktop-wallet/src/components/AssetBadge.tsx
  apps/desktop-wallet/src/components/Inputs/SelectOptionAddress.tsx
  apps/desktop-wallet/src/components/Inputs/SelectOptionItemContent.tsx
  apps/desktop-wallet/src/components/TransactionalInfo.tsx
  apps/desktop-wallet/src/features/assetsLists/AssetsBadgesList.tsx
  apps/desktop-wallet/src/features/assetsLists/FungibleTokensBalancesList.tsx
  apps/desktop-wallet/src/features/assetsLists/useSortedFungibleTokens.tsx
  apps/desktop-wallet/src/pages/UnlockedWallet/AddressesPage/AddressGridRow.tsx
  apps/desktop-wallet/src/storage/addresses/addressesSelectors.ts
Labels: 🖥 DW

#791 Delete many Redux selectors and use Tanstack data
  apps/desktop-wallet/src/api/addressesListedFungibleTokensDataHooks.ts
  apps/desktop-wallet/src/api/addressesUnlistedTokensHooks.ts
  apps/desktop-wallet/src/api/useAddressesDisplayTokens.ts
  apps/desktop-wallet/src/components/Amount.tsx
  apps/desktop-wallet/src/components/Inputs/SelectOptionToken.tsx
  apps/desktop-wallet/src/features/assetsLists/AssetsBadgesList.tsx
  apps/desktop-wallet/src/features/assetsLists/AssetsTabs.tsx
  apps/desktop-wallet/src/features/assetsLists/NonStandardTokensBalancesList.tsx
  apps/desktop-wallet/src/features/assetsLists/TokenBalancesRow.tsx
  apps/desktop-wallet/src/features/assetsLists/useSortedFungibleTokens.tsx
  apps/desktop-wallet/src/modals/SendModals/AssetAmountsInput.tsx
  apps/desktop-wallet/src/modals/SendModals/CheckAmountsBox.tsx
  apps/desktop-wallet/src/modals/TransactionDetailsModal.tsx
  apps/desktop-wallet/src/pages/UnlockedWallet/TransfersPage/FiltersPanel.tsx
  apps/desktop-wallet/src/pages/UnlockedWallet/TransfersPage/index.tsx
  apps/desktop-wallet/src/storage/addresses/addressesSelectors.ts
  apps/desktop-wallet/src/types/tokens.ts
Labels: 🖥 DW

#806 Patch mw
  apps/mobile-wallet/locales/de-DE/translation.json
  apps/mobile-wallet/locales/en-US/translation.json
  apps/mobile-wallet/src/navigation/RootStackNavigation.tsx
  apps/mobile-wallet/src/screens/LandingScreen.tsx
  apps/mobile-wallet/src/screens/Settings/SettingsScreen.tsx
Labels: 📱 MW
