Repository alephium/alephium-frontend, pull requests merged in 2024-10, with the labels that each got.

#868 Skip win sign when rc
  .github/workflows/release-desktop.yml
Labels: 🖥 DW, windows

#857 Delete address
  .changeset/tiny-ties-burn.md
  apps/desktop-wallet/locales/en-US/translation.json
  apps/desktop-wallet/src/features/modals/modalSlice.ts
  apps/desktop-wallet/src/features/modals/modalTypes.ts
  apps/desktop-wallet/src/features/transactionsDisplay/transactionDetailsModal/TransactionDetailsModal.tsx
  apps/desktop-wallet/src/modals/AddressDetailsModal/AddressDetailsModal.tsx
  apps/desktop-wallet/src/modals/AddressDetailsModal/AddressDetailsModalHeader.tsx
  apps/desktop-wallet/src/modals/AddressOptionsModal.tsx
  apps/desktop-wallet/src/modals/AddressSweepModal.tsx
  apps/desktop-wallet/src/modals/CSVExportModal.tsx
  apps/desktop-wallet/src/modals/ReceiveModal.tsx
  apps/desktop-wallet/src/modals/SettingsModal/CopyPrivateKeyConfirmationModal.tsx
  apps/desktop-wallet/src/pages/UnlockedWallet/AddressesPage/AddressesTabContent.tsx
  apps/desktop-wallet/src/pages/UnlockedWallet/AddressesPage/AdvancedOperationsSideModal.tsx
  apps/desktop-wallet/src/storage/addresses/addressMetadataPersistentStorage.ts
  apps/desktop-wallet/src/storage/addresses/addressesActions.ts
  apps/desktop-wallet/src/storage/addresses/addressesSlice.ts
Labels: 🖥 DW

#872 Optimize loading speed by removing addressSingleTokenBalancesQuery
  apps/desktop-wallet/src/api/apiDataHooks/address/useFetchAddressSingleTokenBalances.ts
  apps/desktop-wallet/src/api/apiDataHooks/wallet/combineBalances.ts
  apps/desktop-wallet/src/api/apiDataHooks/wallet/useFetchWalletBalancesAlph.ts
  apps/desktop-wallet/src/api/apiDataHooks/wallet/useFetchWalletSingleTokenBalances.ts
  apps/desktop-wallet/src/api/queries/addressQueries.ts
Labels: 🖥 DW

#894 Post 2.4.0 fixes
  .changeset/clever-flies-explode.md
  apps/desktop-wallet/src/App.tsx
  apps/desktop-wallet/src/api/persistQueryClientContext.tsx
  apps/desktop-wallet/src/api/persistedCacheVersionStorage.ts
  apps/desktop-wallet/src/api/queryClient.ts
  apps/desktop-wallet/src/features/addressDeletion/DeleteAddressesModal.tsx
  apps/desktop-wallet/src/features/walletConnect/WalletConnectSessionProposalModal.tsx
  apps/desktop-wallet/src/features/walletConnect/WalletConnectSessionRequestEventHandler.tsx
  apps/desktop-wallet/src/features/walletConnect/walletConnectContext.tsx
  apps/desktop-wallet/src/hooks/useWalletLock.ts
  apps/desktop-wallet/src/modals/AddressOptionsModal.tsx
  apps/desktop-wallet/src/modals/WalletRemovalModal.tsx
  apps/desktop-wallet/src/pages/NewWallet/CreateWalletPage.tsx
  apps/desktop-wallet/src/routes/UnlockedWalletRoutes.tsx
  apps/desktop-wallet/src/storage/addresses/addressesSelectors.ts
Labels: 🖥 DW

#906 2.4.1 rc fixxes
  apps/desktop-wallet/src/api/apiDataHooks/market/useFetchTokenPrices.ts
  apps/desktop-wallet/src/api/queries/tokenQueries.ts
  apps/desktop-wallet/src/api/queries/transactionQueries.ts
  apps/desktop-wallet/src/features/historicChart/useHistoricData.tsx
  apps/desktop-wallet/src/hooks/useAddresses.ts
Labels: 🖥 DW

#909 Fix Sentry reported bugs
  .changeset/loud-mice-compete.md
  .changeset/nervous-dolls-rest.md
  apps/mobile-wallet/__tests__/wallet.test.ts
  apps/mobile-wallet/setupErrorHandling.ts
  apps/mobile-wallet/src/navigation/RootStackNavigation.tsx
  apps/mobile-wallet/src/persistent-storage/wallet.ts
  apps/mobile-wallet/src/screens/LoginWithPinScreen.tsx
  apps/mobile-wallet/src/store/addressesSlice.ts
  apps/mobile-wallet/src/store/wallet/walletActions.ts
Labels: 📱 MW

#912 Fix apple warning
  apps/mobile-wallet/app.config.js
  apps/mobile-wallet/ios/Alephium/Info.plist
Labels: 📱 MW

#918 Fix 2.4.1
  .changeset/little-owls-fix.md
  .changeset/modern-icons-turn.md
  apps/desktop-wallet/src/App.tsx
  apps/desktop-wallet/src/api/queries/tokenQueries.ts
  apps/desktop-wallet/src/features/autoUpdate/useLatestGitHubRelease.ts
  apps/desktop-wallet/src/hooks/useAutoLock.ts
Labels: 🖥 DW

#922 Update release docs
  apps/desktop-wallet/README.md
  apps/explorer/README.md
  apps/mobile-wallet/README.md
Labels: monorepo

#913 Internationalize desktop wallet amounts based on user's region or choice
  .changeset/breezy-keys-fly.md
  apps/desktop-wallet/locales/en-US/translation.json
  apps/desktop-wallet/public/electron.js
  apps/desktop-wallet/public/preload.js
  apps/desktop-wallet/src/App.tsx
  apps/desktop-wallet/src/components/Amount.tsx
  apps/desktop-wallet/src/components/Inputs/Select.tsx
  apps/desktop-wallet/src/components/SnackbarManager.tsx
  apps/desktop-wallet/src/features/autoUpdate/AutoUpdateSnackbar.tsx
  apps/desktop-wallet/src/features/send/SendModal.tsx
  apps/desktop-wallet/src/features/send/sentTransactions/SentTransactionSnackbarPopup.tsx
  apps/desktop-wallet/src/features/settings/RegionSettings.tsx
  apps/desktop-wallet/src/features/settings/regions.json
  apps/desktop-wallet/src/features/settings/useRegionOptions.ts
  apps/desktop-wallet/src/hooks/useFocusOnMount.tsx
  apps/desktop-wallet/src/modals/SettingsModal/GeneralSettingsSection.tsx
  apps/desktop-wallet/src/storage/settings/settingsActions.ts
  apps/desktop-wallet/src/storage/settings/settingsPersistentStorage.ts
  apps/desktop-wallet/src/storage/settings/settingsSlice.ts
  apps/desktop-wallet/src/tests/settings.test.ts
  apps/desktop-wallet/src/types/settings.ts
  apps/desktop-wallet/src/types/window.d.ts
  packages/shared/src/numbers.ts
  packages/shared/test/numbers-test.ts
Labels: 🖥 DW

#931 Fix display of binary NFT images
  apps/desktop-wallet/src/features/thumbnails/NFTThumbnail.tsx
Labels: 🖥 DW

#932 Address worth improvements/fixes
  .changeset/many-eyes-bow.md
  apps/desktop-wallet/src/api/apiDataHooks/market/useFetchTokenPrices.ts
  apps/explorer/locales/de-DE/translation.json
  apps/explorer/locales/el-GR/translation.json
  apps/explorer/locales/en-US/translation.json
  apps/explorer/locales/fr-FR/translation.json
  apps/explorer/locales/id-ID/translation.json
  apps/explorer/locales/it-IT/translation.json
  apps/explorer/locales/pt-PT/translation.json
  apps/explorer/locales/vi-VN/translation.json
  apps/explorer/src/api/assets/assetsHooks.ts
  apps/explorer/src/pages/AddressInfoPage/AssetList.tsx
  apps/explorer/src/pages/AddressInfoPage/index.tsx
  packages/shared/src/assets.ts
  packages/shared/src/numbers.ts
  packages/shared/test/numbers-test.ts
  pnpm-lock.yaml
Labels: 🔎 XPLR

#940 Do not render badge text if it will be hidden
  apps/desktop-wallet/src/components/TokenBadge.tsx
Labels: 🖥 DW

#942 Fix default lock time
  .changeset/long-cats-deliver.md
  apps/desktop-wallet/src/storage/settings/settingsPersistentStorage.ts
  apps/desktop-wallet/src/utils/settings.ts
Labels: 🖥 DW
