Repository alephium/alephium-frontend, pull requests merged in 2024-02, with the labels that each got.

#341 Fix tx display
  .changeset/silver-cherries-film.md
  apps/desktop-wallet/src/components/TransactionalInfo.tsx
  apps/desktop-wallet/src/types/transactions.ts
  apps/desktop-wallet/src/utils/transactions.ts
  apps/explorer/src/utils/transactions.ts
  apps/mobile-wallet/src/utils/transactions.ts
  packages/shared/lib/transactions.ts
Labels: 📱 MW, 🖥 DW, 🔎 XPLR, 🤲 SHRD

#316 Handle WC request when wallet locks
  .changeset/hungry-bats-smell.md
  apps/desktop-wallet/locales/bg-BG/translation.json
  apps/desktop-wallet/locales/de-DE/translation.json
  apps/desktop-wallet/locales/en-US/translation.json
  apps/desktop-wallet/locales/es-ES/translation.json
  apps/desktop-wallet/locales/fr-FR/translation.json
  apps/desktop-wallet/locales/id-ID/translation.json
  apps/desktop-wallet/locales/it-IT/translation.json
  apps/desktop-wallet/locales/pt-PT/translation.json
  apps/desktop-wallet/locales/ru-RU/translation.json
  apps/desktop-wallet/locales/tr-TR/translation.json
  apps/desktop-wallet/locales/vi-VN/translation.json
  apps/desktop-wallet/src/contexts/walletconnect.tsx
  apps/desktop-wallet/src/pages/HomePage/UnlockPanel.tsx
Labels: WalletConnect, 🖥 DW

#334 Allow wallets to connect to devnet
  .changeset/late-suits-peel.md
  .changeset/rich-timers-bow.md
  .changeset/weak-files-live.md
  apps/desktop-wallet/locales/bg-BG/translation.json
  apps/desktop-wallet/locales/de-DE/translation.json
  apps/desktop-wallet/locales/en-US/translation.json
  apps/desktop-wallet/locales/es-ES/translation.json
  apps/desktop-wallet/locales/fr-FR/translation.json
  apps/desktop-wallet/locales/id-ID/translation.json
  apps/desktop-wallet/locales/it-IT/translation.json
  apps/desktop-wallet/locales/pt-PT/translation.json
  apps/desktop-wallet/locales/ru-RU/translation.json
  apps/desktop-wallet/locales/tr-TR/translation.json
  apps/desktop-wallet/locales/vi-VN/translation.json
  apps/desktop-wallet/src/components/NetworkSwitch.tsx
  apps/desktop-wallet/src/modals/SettingsModal/NetworkSettingsSection.tsx
  apps/desktop-wallet/src/modals/WalletConnect/WalletConnectSessionProposalModal.tsx
  apps/desktop-wallet/src/tests/settings.test.ts
  apps/desktop-wallet/src/types/network.ts
  apps/mobile-wallet/src/contexts/walletConnect/WalletConnectSessionProposalModal.tsx
  apps/mobile-wallet/src/screens/SwitchNetworkModal.tsx
  packages/shared/src/network.ts
  packages/shared/src/types/network.ts
Labels: WalletConnect, 📱 MW, 🖥 DW

#337 Fix display of failed txs in wallets
  .changeset/bright-melons-matter.md
  .changeset/tiny-shirts-whisper.md
  apps/desktop-wallet/locales/bg-BG/translation.json
  apps/desktop-wallet/locales/de-DE/translation.json
  apps/desktop-wallet/locales/en-US/translation.json
  apps/desktop-wallet/locales/es-ES/translation.json
  apps/desktop-wallet/locales/fr-FR/translation.json
  apps/desktop-wallet/locales/id-ID/translation.json
  apps/desktop-wallet/locales/it-IT/translation.json
  apps/desktop-wallet/locales/pt-PT/translation.json
  apps/desktop-wallet/locales/ru-RU/translation.json
  apps/desktop-wallet/locales/tr-TR/translation.json
  apps/desktop-wallet/locales/vi-VN/translation.json
  apps/desktop-wallet/src/components/TransactionalInfo.tsx
  apps/desktop-wallet/src/hooks/useTransactionUI.tsx
  apps/desktop-wallet/src/modals/TransactionDetailsModal.tsx
  apps/mobile-wallet/src/components/TransactionListItem.tsx
  apps/mobile-wallet/src/hooks/useTransactionUI.ts
  apps/mobile-wallet/src/screens/TransactionModal.tsx
Labels: 📱 MW, 🖥 DW

#340 Centralise currencies
  .changeset/cold-sheep-smell.md
  apps/desktop-wallet/src/pages/UnlockedWallet/AddressesPage/AddressGridRow.tsx
  apps/desktop-wallet/src/pages/UnlockedWallet/OverviewPage/AddressesContactsList.tsx
  apps/desktop-wallet/src/pages/UnlockedWallet/OverviewPage/AmountsOverviewPanel.tsx
  apps/desktop-wallet/src/pages/UnlockedWallet/OverviewPage/AssetsList.tsx
  apps/desktop-wallet/src/pages/UnlockedWallet/OverviewPage/GreetingMessages.tsx
  apps/desktop-wallet/src/utils/currencies.ts
  apps/desktop-wallet/src/utils/settings.ts
  apps/mobile-wallet/src/api/price.ts
  apps/mobile-wallet/src/components/AddressCard.tsx
  apps/mobile-wallet/src/components/BalanceSummary.tsx
  apps/mobile-wallet/src/components/HistoricWorthChart.tsx
  apps/mobile-wallet/src/components/WorthDelta.tsx
  apps/mobile-wallet/src/screens/CurrencySelectModal.tsx
  apps/mobile-wallet/src/types/settings.ts
  packages/shared/src/currencies.ts
  packages/shared/src/index.ts
  turbo.json
Labels: 🖥 DW

#285 EAS GitHub workflows
  .github/actions/setup-monorepo/action.yml
  .github/workflows/build-mobile.yml
  apps/mobile-wallet/README.md
  apps/mobile-wallet/app.config.js
  apps/mobile-wallet/eas.json
Labels: 📱 MW, monorepo

#349 Reduce fetch-retry number of tries to 3
  .changeset/big-geese-breathe.md
  apps/explorer/src/App.tsx
Labels: 🔎 XPLR

#270 Add token prices
  apps/explorer/src/api/assets/assetsApi.ts
  apps/explorer/src/api/assets/assetsHooks.ts
  apps/explorer/src/pages/AddressInfoPage/NFTList.tsx
  apps/explorer/src/pages/AddressInfoPage/TokenList.tsx
  apps/explorer/src/pages/AddressInfoPage/index.tsx
  apps/explorer/src/utils/api.ts
Labels: 🔎 XPLR
