Repository alephium/alephium-frontend, pull requests merged in 2024-07, with the labels that each got.

#704 Replaced deprecated history call (rebased)
  apps/desktop-wallet/src/components/HistoricWorthChart.tsx
  apps/desktop-wallet/src/storage/addresses/addressesActions.ts
  apps/mobile-wallet/src/store/addressesSlice.ts
  apps/mobile-wallet/src/store/loadersSlice.ts
Labels: 🖥 DW

#585 Expo 51
  apps/desktop-wallet/package.json
  apps/desktop-wallet/src/components/HistoricWorthChart.tsx
  apps/desktop-wallet/src/storage/addresses/addressesActions.ts
  apps/explorer/package.json
  apps/mobile-wallet/android/.gitignore
  apps/mobile-wallet/android/app/build.gradle
  apps/mobile-wallet/android/app/src/main/AndroidManifest.xml
  apps/mobile-wallet/android/app/src/main/java/org/alephium/wallet/MainApplication.kt
  apps/mobile-wallet/android/app/src/main/res/drawable/rn_edit_text_material.xml
  apps/mobile-wallet/android/app/src/main/res/values/styles.xml
  apps/mobile-wallet/android/build.gradle
  apps/mobile-wallet/android/gradle.properties
  apps/mobile-wallet/android/gradle/wrapper/gradle-wrapper.properties
  apps/mobile-wallet/android/gradlew.bat
  apps/mobile-wallet/app.config.js
  apps/mobile-wallet/ios/Alephium.xcodeproj/project.pbxproj
  apps/mobile-wallet/ios/Alephium/AppDelegate.mm
  apps/mobile-wallet/ios/Alephium/Info.plist
  apps/mobile-wallet/ios/Alephium/PrivacyInfo.xcprivacy
  apps/mobile-wallet/ios/Alephium/Supporting/Expo.plist
  apps/mobile-wallet/ios/Podfile
  apps/mobile-wallet/ios/Podfile.lock
  apps/mobile-wallet/ios/Podfile.properties.json
  apps/mobile-wallet/package.json
  apps/mobile-wallet/shim.ts
  apps/mobile-wallet/src/components/QRCodeScannerModal.tsx
  apps/mobile-wallet/src/screens/LandingScreen.tsx
  apps/mobile-wallet/src/screens/SendReceive/Send/AssetsScreen/AssetRow.tsx
  apps/mobile-wallet/src/store/addressesSlice.ts
  apps/mobile-wallet/src/store/loadersSlice.ts
  packages/keyring/package.json
  packages/shared-react/package.json
  packages/shared/package.json
  pnpm-lock.yaml
Labels: 📱 MW

#705 Improve cold start by preloading data
  .changeset/grumpy-weeks-repeat.md
  apps/mobile-wallet/src/App.tsx
  apps/mobile-wallet/src/contexts/walletConnect/WalletConnectContext.tsx
  apps/mobile-wallet/src/store/addressesSlice.ts
  apps/mobile-wallet/src/store/appSlice.ts
  apps/mobile-wallet/src/store/wallet/walletActions.ts
  apps/mobile-wallet/src/store/wallet/walletSlice.ts
Labels: 📱 MW

#707 Improve NFT loading
  .changeset/stupid-books-share.md
  .changeset/sweet-nails-appear.md
  .changeset/two-beans-peel.md
  apps/desktop-wallet/src/modals/NFTDetailsModal.tsx
  apps/mobile-wallet/ios/Podfile.lock
  apps/mobile-wallet/locales/en-US/translation.json
  apps/mobile-wallet/package.json
  apps/mobile-wallet/src/App.tsx
  apps/mobile-wallet/src/components/AssetAmountWithLogo.tsx
  apps/mobile-wallet/src/components/NFTImage.tsx
  apps/mobile-wallet/src/components/NFTModal.tsx
  apps/mobile-wallet/src/components/NFTPlaceholder.tsx
  apps/mobile-wallet/src/components/NFTThumbnail.tsx
  apps/mobile-wallet/src/components/NFTWebView.tsx
  apps/mobile-wallet/src/components/NFTsGrid.tsx
  apps/mobile-wallet/src/screens/SendReceive/Send/AssetsScreen/AssetRow.tsx
  apps/mobile-wallet/src/screens/TransactionModal.tsx
  packages/shared/package.json
  packages/shared/src/store/assets/assetsActions.ts
  pnpm-lock.yaml
Labels: 📱 MW

#717 Visual bug fixes
  apps/mobile-wallet/locales/de-DE/translation.json
  apps/mobile-wallet/locales/el-GR/translation.json
  apps/mobile-wallet/locales/en-US/translation.json
  apps/mobile-wallet/locales/fr-FR/translation.json
  apps/mobile-wallet/locales/pt-PT/translation.json
  apps/mobile-wallet/locales/vi-VN/translation.json
  apps/mobile-wallet/src/components/AddressBox.tsx
  apps/mobile-wallet/src/components/AssetLogo.tsx
  apps/mobile-wallet/src/components/NFTPlaceholder.tsx
  apps/mobile-wallet/src/components/NFTWebView.tsx
  apps/mobile-wallet/src/features/auto-lock/AutoLockOptionsModal.tsx
  apps/mobile-wallet/src/features/localization/LanguageSelectModal.tsx
  apps/mobile-wallet/src/screens/Addresses/Address/GroupSelectModal.tsx
  apps/mobile-wallet/src/screens/CurrencySelectModal.tsx
  apps/mobile-wallet/src/screens/SwitchNetworkModal.tsx
Labels: 📱 MW

#703 Show uncle blocks (rebased)
  .changeset/tender-ligers-cross.md
  apps/desktop-wallet/package.json
  apps/desktop-wallet/src/storage/addresses/addressesActions.ts
  apps/explorer/locales/de-DE/translation.json
  apps/explorer/locales/el-GR/translation.json
  apps/explorer/locales/en-US/translation.json
  apps/explorer/locales/fr-FR/translation.json
  apps/explorer/locales/id-ID/translation.json
  apps/explorer/locales/vi-VN/translation.json
  apps/explorer/package.json
  apps/explorer/src/App.tsx
  apps/explorer/src/api/addresses/addressApi.ts
  apps/explorer/src/api/assets/assetsApi.ts
  apps/explorer/src/api/blocks/blocksApi.ts
  apps/explorer/src/api/infos/infosApi.ts
  apps/explorer/src/api/transactions/transactionsApi.ts
  apps/explorer/src/components/Badge.tsx
  apps/explorer/src/components/Links.tsx
  apps/explorer/src/components/LoadingSpinner.tsx
  apps/explorer/src/components/SectionTitle.tsx
  apps/explorer/src/pages/AddressInfoPage/index.tsx
  apps/explorer/src/pages/BlockInfoPage.tsx
  apps/explorer/src/utils/api.ts
  apps/mobile-wallet/package.json
  packages/keyring/package.json
  packages/shared/package.json
  packages/shared/test/fixtures/transactions.json
  pnpm-lock.yaml
Labels: 🔎 XPLR

#734 Change Alephium logo import style
  apps/explorer/src/components/AssetLogo.tsx
  apps/explorer/src/components/SearchBar.tsx
  apps/explorer/src/pages/HomePage/HomePage.tsx
Labels: 🔎 XPLR

#737 Fetch NFT collection data and ALPH historical prices with Tanstack
  apps/desktop-wallet/package.json
  apps/desktop-wallet/src/App.tsx
  apps/desktop-wallet/src/components/HistoricWorthChart.tsx
  apps/desktop-wallet/src/features/tokenPrices/tokenPricesHooks.tsx
  apps/desktop-wallet/src/index.tsx
  apps/desktop-wallet/src/modals/NFTDetailsModal.tsx
  apps/desktop-wallet/src/storage/addresses/addressesSelectors.ts
  apps/desktop-wallet/src/storage/store.ts
  apps/explorer/package.json
  apps/explorer/src/App.tsx
  apps/mobile-wallet/package.json
  packages/keyring/package.json
  packages/shared/package.json
  packages/shared/src/api/index.ts
  packages/shared/src/api/nftsApi.ts
  packages/shared/src/store/prices/pricesSelectors.ts
  packages/shared/src/store/store.ts
  pnpm-lock.yaml
Labels: 🖥 DW

#746 Return first address if default not found
  .changeset/moody-peaches-peel.md
  .github/workflows/release-desktop.yml
  apps/desktop-wallet/package.json
  apps/desktop-wallet/src/hooks/useAddressGeneration.tsx
  apps/desktop-wallet/src/modals/SettingsModal/DevToolsSettingsSection.tsx
  apps/desktop-wallet/src/storage/addresses/addressesSelectors.ts
  pnpm-lock.yaml
Labels: 🖥 DW

#745 Fetch token balances with Tanstack
  apps/desktop-wallet/locales/en-US/translation.json
  apps/desktop-wallet/src/App.tsx
  apps/desktop-wallet/src/api/addressQueries.ts
  apps/desktop-wallet/src/api/addressTransactionsDataHooks.ts
  apps/desktop-wallet/src/api/addressesBalancesDataHooks.ts
  apps/desktop-wallet/src/api/addressesFungibleTokensInfoDataHooks.tsx
  apps/desktop-wallet/src/api/addressesFungibleTokensPricesDataHooks.tsx
  apps/desktop-wallet/src/api/fungibleTokenListDataHooks.ts
  apps/desktop-wallet/src/api/queryClient.ts
  apps/desktop-wallet/src/api/transactionQueries.ts
  apps/desktop-wallet/src/components/Inputs/AddressSelect.tsx
  apps/desktop-wallet/src/components/Inputs/SelectOptionAddress.tsx
  apps/desktop-wallet/src/features/balancesOverview/TotalAlphBalance.tsx
  apps/desktop-wallet/src/features/historicChart/HistoricWorthChart.tsx
  apps/desktop-wallet/src/features/historicChart/useHistoricData.tsx
  apps/desktop-wallet/src/index.tsx
  apps/desktop-wallet/src/modals/WalletConnect/WalletConnectSessionProposalModal.tsx
  apps/desktop-wallet/src/pages/UnlockedWallet/AddressesPage/AddressGridRow.tsx
  apps/desktop-wallet/src/pages/UnlockedWallet/OverviewPage/AddressesContactsList.tsx
  apps/desktop-wallet/src/pages/UnlockedWallet/OverviewPage/AmountsOverviewPanel.tsx
  apps/desktop-wallet/src/pages/UnlockedWallet/OverviewPage/AssetsList.tsx
  apps/desktop-wallet/src/pages/UnlockedWallet/OverviewPage/GreetingMessages.tsx
  apps/desktop-wallet/src/pages/UnlockedWallet/TransfersPage/FiltersPanel.tsx
  apps/desktop-wallet/src/storage/addresses/addressesSelectors.ts
  apps/desktop-wallet/src/storage/transactions/transactionsSelectors.ts
  packages/shared/src/types/assets.ts
Labels: 🖥 DW
