Repository alephium/alephium-frontend, pull requests merged in 2025-01, with the labels that each got.

#1075 Fix MW redesign UI bugs
  apps/mobile-wallet/package.json
  apps/mobile-wallet/src/api/addresses.ts
  apps/mobile-wallet/src/components/AddressBox.tsx
  apps/mobile-wallet/src/components/Amount.tsx
  apps/mobile-wallet/src/features/transactionsDisplay/TransactionModal.tsx
  apps/mobile-wallet/src/screens/Dashboard/WalletConnectButton.tsx
  apps/mobile-wallet/src/store/addressesSlice.ts
  apps/mobile-wallet/src/store/store.ts
  pnpm-lock.yaml
Labels: 📱 MW

#1074 Fix retry
  apps/mobile-wallet/src/api/addresses.ts
  apps/mobile-wallet/src/api/transactions.ts
  apps/mobile-wallet/src/contexts/walletConnect/WalletConnectContext.tsx
  apps/mobile-wallet/src/store/addressDiscoverySlice.ts
  apps/mobile-wallet/src/store/addressesSlice.ts
  packages/shared/src/api/client.ts
  packages/shared/src/api/fetchRetry.ts
Labels: 📱 MW

#1081 Redesign polish ilias
  apps/mobile-wallet/locales/en-US/translation.json
  apps/mobile-wallet/src/components/AddressBox.tsx
  apps/mobile-wallet/src/components/AddressesTokensList.tsx
  apps/mobile-wallet/src/components/headers/BaseHeader.tsx
  apps/mobile-wallet/src/screens/Dashboard/DashboardScreen.tsx
Labels: 📱 MW

#1080 Redesign polish + add branding
  apps/mobile-wallet/ios/Alephium.xcodeproj/project.pbxproj
  apps/mobile-wallet/ios/Alephium/PrivacyInfo.xcprivacy
  apps/mobile-wallet/ios/Podfile.lock
  apps/mobile-wallet/locales/en-US/translation.json
  apps/mobile-wallet/src/components/AddressBox.tsx
  apps/mobile-wallet/src/components/AddressesTokensList.tsx
  apps/mobile-wallet/src/components/headers/BaseHeader.tsx
  apps/mobile-wallet/src/components/layout/FlashListScreen.tsx
  apps/mobile-wallet/src/components/layout/ScrollScreen.tsx
  apps/mobile-wallet/src/features/buy/BuyModal.tsx
  apps/mobile-wallet/src/screens/Dashboard/DashboardScreen.tsx
  apps/mobile-wallet/src/screens/Dashboard/DashboardSecondaryButtons.tsx
Labels: 📱 MW

#1086 Fix data loading in mobile wallet
  .changeset/large-flowers-eat.md
  apps/mobile-wallet/src/api/addresses.ts
  apps/mobile-wallet/src/components/layout/TransactionsFlashList.tsx
  apps/mobile-wallet/src/screens/ActivityScreen.tsx
  apps/mobile-wallet/src/store/addressesSlice.ts
  apps/mobile-wallet/src/store/confirmedTransactionsSlice.ts
  apps/mobile-wallet/src/store/pendingTransactionsSlice.ts
  packages/shared/src/constants.ts
Labels: 📱 MW

#1092 Remove listener removal
  apps/mobile-wallet/src/features/buy/BuyModal.tsx
  apps/mobile-wallet/src/features/buy/buyUtils.ts
Labels: 📱 MW

#1088 Optimize txs loading in desktop wallet (remove POST)
  .changeset/six-rivers-hang.md
  apps/desktop-wallet/locales/en-US/translation.json
  apps/desktop-wallet/src/api/apiDataHooks/wallet/useFetchWalletTransactionsInfinite.ts
  apps/desktop-wallet/src/api/apiDataHooks/wallet/useFetchWalletTransactionsLimited.tsx
  apps/desktop-wallet/src/api/context/apiContext.tsx
  apps/desktop-wallet/src/api/queries/transactionQueries.ts
  apps/desktop-wallet/src/components/AppHeader.tsx
  apps/desktop-wallet/src/features/transactionsDisplay/transactionLists/AddressLimitWarning.tsx
  apps/desktop-wallet/src/features/transactionsDisplay/transactionLists/lists/WalletLatestTransactionsList.tsx
  apps/desktop-wallet/src/features/transactionsDisplay/transactionLists/lists/WalletTransactionsList.tsx
  apps/desktop-wallet/src/hooks/useAddresses.ts
  apps/desktop-wallet/src/pages/UnlockedWallet/TransfersPage/index.tsx
Labels: 🖥 DW

#1097 Pre v2.0 fixes
  apps/mobile-wallet/src/components/layout/TransactionsFlashList.tsx
  apps/mobile-wallet/src/features/modals/useBottomModalState.tsx
  apps/mobile-wallet/src/screens/new-wallet/DecryptScannedMnemonicScreen.tsx
Labels: 📱 MW

#1096 Support alph_signAndSubmitUnsignedTx
  .changeset/purple-wasps-compete.md
  .changeset/red-cows-fly.md
  .changeset/strange-candles-crash.md
  .changeset/thin-steaks-melt.md
  apps/desktop-wallet/locales/en-US/translation.json
  apps/desktop-wallet/src/features/walletConnect/SignUnsignedTxModal.tsx
  apps/desktop-wallet/src/features/walletConnect/WalletConnectSessionRequestEventHandler.tsx
  apps/mobile-wallet/src/contexts/walletConnect/WalletConnectContext.tsx
  apps/mobile-wallet/src/contexts/walletConnect/WalletConnectSessionRequestModal.tsx
  apps/mobile-wallet/src/types/walletConnect.ts
Labels: 📱 MW, 🖥 DW

#1106 Fix iOS crash due to SpinnerModal
  apps/mobile-wallet/CHANGELOG.md
  apps/mobile-wallet/locales/en-US/translation.json
  apps/mobile-wallet/src/App.tsx
  apps/mobile-wallet/src/components/AddressCard.tsx
  apps/mobile-wallet/src/components/DeprecatedAuthenticationModal.tsx
  apps/mobile-wallet/src/contexts/walletConnect/WalletConnectContext.tsx
  apps/mobile-wallet/src/contexts/walletConnect/WalletConnectSessionProposalModal.tsx
  apps/mobile-wallet/src/contexts/walletConnect/WalletConnectSessionRequestModal.tsx
  apps/mobile-wallet/src/features/loader/LoadingManager.tsx
  apps/mobile-wallet/src/features/loader/SpinnerModal.tsx
  apps/mobile-wallet/src/features/loader/loaderActions.ts
  apps/mobile-wallet/src/features/loader/loaderSlice.ts
  apps/mobile-wallet/src/features/send/screens/AssetsScreen/index.tsx
  apps/mobile-wallet/src/features/settings/EditWalletNameModal.tsx
  apps/mobile-wallet/src/features/settings/WalletDeleteModal.tsx
  apps/mobile-wallet/src/features/walletconnect/WalletConnectPasteUrlModal.tsx
  apps/mobile-wallet/src/screens/AddressDiscoveryScreen.tsx
  apps/mobile-wallet/src/screens/Addresses/Address/EditAddressScreen.tsx
  apps/mobile-wallet/src/screens/Addresses/Address/NewAddressScreen.tsx
  apps/mobile-wallet/src/screens/Addresses/Contact/EditContactScreen.tsx
  apps/mobile-wallet/src/screens/Addresses/Contact/NewContactScreen.tsx
  apps/mobile-wallet/src/screens/CustomNetworkScreen.tsx
  apps/mobile-wallet/src/screens/LoginWithPinScreen.tsx
  apps/mobile-wallet/src/screens/new-wallet/DecryptScannedMnemonicScreen.tsx
  apps/mobile-wallet/src/screens/new-wallet/NewWalletNameScreen.tsx
  apps/mobile-wallet/src/store/store.ts
Labels: 📱 MW

#1108 Fix prices on mobile wallet
  apps/mobile-wallet/CHANGELOG.md
  apps/mobile-wallet/src/App.tsx
  apps/mobile-wallet/src/store/addressesSlice.ts
Labels: 📱 MW

#1101 Redesigned addresses screen
  apps/mobile-wallet/locales/en-US/translation.json
  apps/mobile-wallet/src/components/AddressBadge.tsx
  apps/mobile-wallet/src/components/AddressBox.tsx
  apps/mobile-wallet/src/components/AddressCard.tsx
  apps/mobile-wallet/src/components/AddressColorSymbol.tsx
  apps/mobile-wallet/src/components/AddressesTokensList.tsx
  apps/mobile-wallet/src/components/AnimatedBackground.tsx
  apps/mobile-wallet/src/components/BalanceSummary.tsx
  apps/mobile-wallet/src/components/BiometricsWarningModal.tsx
  apps/mobile-wallet/src/components/EmptyPlaceholder.tsx
  apps/mobile-wallet/src/components/ExpandableRow.tsx
  apps/mobile-wallet/src/components/Row.tsx
  apps/mobile-wallet/src/components/TopTabBar.tsx
  apps/mobile-wallet/src/components/buttons/ActionCardButton.tsx
  apps/mobile-wallet/src/components/buttons/Button.tsx
  apps/mobile-wallet/src/components/headers/BaseHeader.tsx
  apps/mobile-wallet/src/components/inputs/ColorPicker.tsx
  apps/mobile-wallet/src/components/inputs/Input.tsx
  apps/mobile-wallet/src/components/layout/FlashListScreen.tsx
  apps/mobile-wallet/src/components/layout/ScreenTitle.tsx
  apps/mobile-wallet/src/components/layout/ScrollScreen.tsx
  apps/mobile-wallet/src/components/layout/TransactionsFlashList.tsx
  apps/mobile-wallet/src/features/address-deletion/AddressCardDeleteButton.tsx
  apps/mobile-wallet/src/features/addressesManagement/AddressDetailsModal.tsx
  apps/mobile-wallet/src/features/addressesManagement/AddressSettingsModal.tsx
  apps/mobile-wallet/src/features/addressesManagement/useCanDeleteAddress.tsx
  apps/mobile-wallet/src/features/localization/LanguageSelectModal.tsx
  apps/mobile-wallet/src/features/modals/AppModals.tsx
  apps/mobile-wallet/src/features/modals/BottomModal.tsx
  apps/mobile-wallet/src/features/modals/BottomModalBase.tsx
  apps/mobile-wallet/src/features/modals/BottomModalHeader.tsx
  apps/mobile-wallet/src/features/modals/modalTypes.ts
  apps/mobile-wallet/src/features/modals/useBottomModalState.tsx
  apps/mobile-wallet/src/features/nftsDisplay/NftModal.tsx
  apps/mobile-wallet/src/features/receive/ReceiveQRCodeModal.tsx
  apps/mobile-wallet/src/features/receive/ReceiveQRCodeSection.tsx
  apps/mobile-wallet/src/features/receive/screens/QRCodeScreen.tsx
  apps/mobile-wallet/src/features/settings/CurrencySelectModal.tsx
  apps/mobile-wallet/src/images/DefaultAddressBadge.tsx
  apps/mobile-wallet/src/navigation/RootStackNavigation.tsx
  apps/mobile-wallet/src/navigation/rootStackRoutes.ts
  apps/mobile-wallet/src/screens/Addresses/Address/AddressForm.tsx
  apps/mobile-wallet/src/screens/Addresses/Address/AddressFormBaseScreen.tsx
  apps/mobile-wallet/src/screens/Addresses/Address/EditAddressScreen.tsx
  apps/mobile-wallet/src/screens/Addresses/Address/GroupSelectModal.tsx
  apps/mobile-wallet/src/screens/Addresses/Address/NewAddressScreen.tsx
  apps/mobile-wallet/src/screens/Addresses/AddressesScreen.tsx
  apps/mobile-wallet/src/screens/Dashboard/DashboardScreen.tsx
  apps/mobile-wallet/src/style/globalStyle.ts
  apps/mobile-wallet/src/style/themes.ts
  apps/mobile-wallet/src/utils/colors.ts
Labels: 📱 MW

#1114 Fix empty placeholders
  apps/mobile-wallet/src/components/AddressesTokensList.tsx
  apps/mobile-wallet/src/components/EmptyPlaceholder.tsx
  apps/mobile-wallet/src/screens/Dashboard/DashboardScreen.tsx
Labels: 📱 MW

#1115 Default AnimatedBackground width to screenwidth
  apps/mobile-wallet/src/components/AnimatedBackground.tsx
  apps/mobile-wallet/src/screens/LandingScreen.tsx
Labels: 📱 MW

#1130 Pre 2.5.1 release fixes
  .changeset/warm-jokes-live.md
  apps/desktop-wallet/package.json
  apps/desktop-wallet/src/api/apiDataHooks/utils/useMergeAllTokensBalances.ts
  apps/desktop-wallet/src/components/Inputs/SelectOptionAddress.tsx
  apps/desktop-wallet/src/components/Inputs/SelectOptionItemContent.tsx
  apps/desktop-wallet/src/features/walletConnect/WalletConnectSessionProposalModal.tsx
  apps/desktop-wallet/src/features/walletConnect/useSignerAddress.ts
Labels: 🖥 DW

#1117 Create token details modal
  .changeset/brave-worms-double.md
  .changeset/happy-socks-share.md
  .changeset/selfish-mugs-hang.md
  apps/mobile-wallet/locales/en-US/translation.json
  apps/mobile-wallet/src/components/AddressBox.tsx
  apps/mobile-wallet/src/components/AddressesTokensList.tsx
  apps/mobile-wallet/src/components/BalanceSummary.tsx
  apps/mobile-wallet/src/components/TokenListItem.tsx
  apps/mobile-wallet/src/features/addressesManagement/AddressDetailsModal.tsx
  apps/mobile-wallet/src/features/addressesManagement/AddressQuickActionsModal.tsx
  apps/mobile-wallet/src/features/addressesManagement/AddressSettingsModal.tsx
  apps/mobile-wallet/src/features/addressesManagement/useForgetAddress.ts
  apps/mobile-wallet/src/features/buy/ActionCardBuyButton.tsx
  apps/mobile-wallet/src/features/modals/AppModals.tsx
  apps/mobile-wallet/src/features/modals/BottomModalHeader.tsx
  apps/mobile-wallet/src/features/modals/modalTypes.ts
  apps/mobile-wallet/src/features/receive/ActionCardReceiveButton.tsx
  apps/mobile-wallet/src/features/send/ActionCardSendButton.tsx
  apps/mobile-wallet/src/features/tokenDisplay/tokenDetailsModal/AddressesWithTokenModal.tsx
  apps/mobile-wallet/src/features/tokenDisplay/tokenDetailsModal/TokenDetailsModal.tsx
  apps/mobile-wallet/src/features/tokenDisplay/tokenDetailsModal/TokenDetailsModalBalanceSummary.tsx
  apps/mobile-wallet/src/features/tokenDisplay/tokenDetailsModal/TokenDetailsModalDescription.tsx
  apps/mobile-wallet/src/features/tokenDisplay/tokenDetailsModal/TokenDetailsModalHeader.tsx
  apps/mobile-wallet/src/features/tokenDisplay/tokenDetailsModal/tokenDetailsModalTypes.ts
  apps/mobile-wallet/src/screens/Dashboard/DashboardScreen.tsx
  apps/mobile-wallet/src/store/addresses/addressesSelectors.ts
  packages/shared/src/types/assets.ts
Labels: 📱 MW

#1133 Pre 2.0.0 fixes
  .changeset/large-beds-report.md
  .changeset/weak-teachers-jog.md
  apps/mobile-wallet/src/components/AddressBadge.tsx
  apps/mobile-wallet/src/components/AddressBox.tsx
  apps/mobile-wallet/src/components/AppText.tsx
  apps/mobile-wallet/src/components/ListItem.tsx
  apps/mobile-wallet/src/components/Row.tsx
  apps/mobile-wallet/src/features/addressesManagement/AddressSettingsModal.tsx
  apps/mobile-wallet/src/features/receive/ReceiveQRCodeSection.tsx
  apps/mobile-wallet/src/features/settings/settingsScreen/SettingsScreen.tsx
  apps/mobile-wallet/src/features/settings/settingsScreen/SettingsSecuritySection.tsx
  apps/mobile-wallet/src/features/transactionsDisplay/TransactionModal.tsx
  apps/mobile-wallet/src/navigation/RootStackNavigation.tsx
  apps/mobile-wallet/src/screens/Addresses/Contact/ContactScreen.tsx
Labels: 📱 MW

#1137 Enable Thai language in mobile wallet
  .changeset/nice-buckets-applaud.md
  apps/mobile-wallet/src/features/localization/i18n.ts
  apps/mobile-wallet/src/features/localization/languages.ts
  apps/mobile-wallet/src/features/localization/useLocalization.ts
Labels: 📱 MW

#1134 Token screen mika rebased + polish
  .changeset/brave-worms-double.md
  .changeset/gold-rabbits-kneel.md
  .changeset/happy-socks-share.md
  .changeset/large-beds-report.md
  .changeset/red-cows-fly.md
  .changeset/selfish-mugs-hang.md
  .changeset/weak-teachers-jog.md
  apps/mobile-wallet/CHANGELOG.md
  apps/mobile-wallet/ios/Podfile.lock
  apps/mobile-wallet/locales/de-DE/translation.json
  apps/mobile-wallet/locales/el-GR/translation.json
  apps/mobile-wallet/locales/en-US/translation.json
  apps/mobile-wallet/locales/fr-FR/translation.json
  apps/mobile-wallet/locales/pt-PT/translation.json
  apps/mobile-wallet/locales/th-TH/translation.json
  apps/mobile-wallet/locales/vi-VN/translation.json
  apps/mobile-wallet/locales/zh-CN/translation.json
  apps/mobile-wallet/package.json
  apps/mobile-wallet/src/components/AddressBox.tsx
  apps/mobile-wallet/src/components/AnimatedBackground.tsx
  apps/mobile-wallet/src/components/EmptyPlaceholder.tsx
  apps/mobile-wallet/src/components/buttons/ActionCardButton.tsx
  apps/mobile-wallet/src/components/buttons/BottomButtons.tsx
  apps/mobile-wallet/src/components/headers/BaseHeader.tsx
  apps/mobile-wallet/src/components/headers/StackHeader.tsx
  apps/mobile-wallet/src/components/inputs/Input.tsx
  apps/mobile-wallet/src/components/layout/TransactionsFlashList.tsx
  apps/mobile-wallet/src/components/toasts/Toast.tsx
  apps/mobile-wallet/src/contexts/HeaderContext.tsx
  apps/mobile-wallet/src/features/addressesManagement/AddressDetailsModal.tsx
  apps/mobile-wallet/src/features/addressesManagement/AddressQuickActionsModal.tsx
  apps/mobile-wallet/src/features/modals/BottomModal.tsx
  apps/mobile-wallet/src/features/modals/BottomModalBase.tsx
  apps/mobile-wallet/src/features/modals/BottomModalFlashList.tsx
  apps/mobile-wallet/src/features/modals/BottomModalHeader.tsx
  apps/mobile-wallet/src/features/modals/useBottomModalState.tsx
  apps/mobile-wallet/src/features/receive/screens/QRCodeScreen.tsx
  apps/mobile-wallet/src/features/send/modals/TokenAmountModal.tsx
  apps/mobile-wallet/src/features/send/screens/DestinationScreen.tsx
  apps/mobile-wallet/src/features/send/screens/VerifyScreen.tsx
  apps/mobile-wallet/src/features/tokenDisplay/tokenDetailsModal/AddressesWithTokenModal.tsx
  apps/mobile-wallet/src/features/tokenDisplay/tokenDetailsModal/TokenDetailsModal.tsx
  apps/mobile-wallet/src/features/tokenDisplay/tokenDetailsModal/TokenDetailsModalBalanceSummary.tsx
  apps/mobile-wallet/src/features/tokenDisplay/tokenDetailsModal/TokenDetailsModalHeader.tsx
  apps/mobile-wallet/src/images/logos/AlephiumLogo.tsx
  apps/mobile-wallet/src/navigation/ReceiveNavigation.tsx
  apps/mobile-wallet/src/navigation/SendNavigation.tsx
  apps/mobile-wallet/src/navigation/useOnChildNavigationGoBack.tsx
  apps/mobile-wallet/src/screens/Dashboard/DashboardScreen.tsx
  apps/mobile-wallet/src/screens/Dashboard/DashboardSecondaryButtons.tsx
  apps/mobile-wallet/src/screens/LandingScreen.tsx
  apps/mobile-wallet/src/screens/new-wallet/NewWalletSuccessScreen.tsx
  apps/mobile-wallet/src/style/themes.ts
  package.json
  pnpm-lock.yaml
Labels: 📱 MW

#1141 Fix auto update
  .changeset/gold-rabbits-nail.md
  apps/desktop-wallet/electron/appProtocol.ts
  apps/desktop-wallet/electron/main.ts
  apps/desktop-wallet/electron/paths.ts
  apps/desktop-wallet/electron/utils.ts
  apps/desktop-wallet/electron/walletConnect.ts
  apps/desktop-wallet/src/features/autoUpdate/AutoUpdateSnackbar.tsx
  apps/desktop-wallet/src/features/autoUpdate/useLatestGitHubRelease.ts
Labels: 🖥 DW

#1149 Close modals on back press
  .changeset/eleven-jokes-smile.md
  apps/mobile-wallet/src/features/modals/BottomModalBase.tsx
Labels: 📱 MW

#1153 Fix password requirement for Ledger wallets
  .changeset/three-files-cross.md
  apps/desktop-wallet/src/features/analytics/useTrackUserSettings.ts
  apps/desktop-wallet/src/features/send/SendModal.tsx
  apps/desktop-wallet/src/features/send/StepsProgress.tsx
  apps/desktop-wallet/src/features/send/sendModals/callContract/CheckTxModalContent.tsx
  apps/desktop-wallet/src/features/send/sendModals/deployContract/CheckTxModalContent.tsx
  apps/desktop-wallet/src/features/send/sendModals/transfer/CheckTxModalContent.tsx
  apps/desktop-wallet/src/features/settings/settingsSelectors.ts
  apps/desktop-wallet/src/modals/SettingsModal/GeneralSettingsSection.tsx
Labels: bug, 🖥 DW

#1157 Fix hidden assets on network switch
  apps/mobile-wallet/src/components/AddressesTokensList.tsx
  apps/mobile-wallet/src/features/assetsDisplay/hideAssets/HiddenAssetsScreen.tsx
  apps/mobile-wallet/src/features/assetsDisplay/hideAssets/SelectAssetToHideModal.tsx
  apps/mobile-wallet/src/features/assetsDisplay/hideAssets/hiddenAssetsSelectors.ts
  apps/mobile-wallet/src/features/settings/settingsScreen/SettingsAssetsSection.tsx
  apps/mobile-wallet/src/features/settings/settingsScreen/SettingsScreen.tsx
  apps/mobile-wallet/src/store/addresses/addressesSelectors.ts
Labels: 📱 MW

#1152 Fix send flow navigation initialization
  apps/mobile-wallet/src/components/AddressBox.tsx
  apps/mobile-wallet/src/components/AddressFlashListScreen.tsx
  apps/mobile-wallet/src/contexts/SendContext.tsx
  apps/mobile-wallet/src/features/assetsDisplay/tokenDisplay/tokenDetailsModal/AddressesWithTokenModal.tsx
  apps/mobile-wallet/src/features/assetsDisplay/tokenDisplay/tokenDetailsModal/TokenDetailsModal.tsx
  apps/mobile-wallet/src/features/backup/backupScreens/BackupIntroScreen.tsx
  apps/mobile-wallet/src/features/receive/ActionCardReceiveButton.tsx
  apps/mobile-wallet/src/features/receive/screens/AddressScreen.tsx
  apps/mobile-wallet/src/features/receive/screens/QRCodeScreen.tsx
  apps/mobile-wallet/src/features/send/ActionCardSendButton.tsx
  apps/mobile-wallet/src/features/send/screens/AssetsScreen/index.tsx
  apps/mobile-wallet/src/features/send/screens/DestinationScreen.tsx
  apps/mobile-wallet/src/features/send/screens/OriginScreen.tsx
  apps/mobile-wallet/src/features/send/screens/VerifyScreen.tsx
  apps/mobile-wallet/src/navigation/SendNavigation.tsx
  apps/mobile-wallet/src/navigation/rootStackRoutes.ts
  apps/mobile-wallet/src/screens/Addresses/Contact/ContactScreen.tsx
  apps/mobile-wallet/src/screens/Dashboard/CameraScanButton.tsx
  apps/mobile-wallet/src/screens/Dashboard/DashboardScreen.tsx
  apps/mobile-wallet/src/screens/Dashboard/DashboardSecondaryButtons.tsx
  apps/mobile-wallet/src/screens/Dashboard/WalletSettingsButton.tsx
Labels: 📱 MW

#1175 Experiment with dynamic colors in AddressDetailsModalHeader tabs
  apps/mobile-wallet/src/components/TokenListItem.tsx
  apps/mobile-wallet/src/features/addressesManagement/AddressDetailsModalHeader.tsx
  apps/mobile-wallet/src/style/themes.ts
Labels: 📱 MW

#1173 Adapt TopBar style to be more consistent with DW
  apps/mobile-wallet/src/components/AddressBadge.tsx
  apps/mobile-wallet/src/components/AddressBox.tsx
  apps/mobile-wallet/src/components/AddressColorSymbol.tsx
  apps/mobile-wallet/src/components/TopTabBar.tsx
  apps/mobile-wallet/src/features/addressesManagement/AddressDetailsModal.tsx
  apps/mobile-wallet/src/navigation/AddressesTabNavigation.tsx
  apps/mobile-wallet/src/screens/Addresses/AddressesScreen.tsx
  apps/mobile-wallet/src/screens/Addresses/ContactsScreen.tsx
  apps/mobile-wallet/src/utils/colors.ts
Labels: 📱 MW

#1177 Scale balance font-size to fit
  apps/mobile-wallet/CHANGELOG.md
  apps/mobile-wallet/src/components/AddressBox.tsx
  apps/mobile-wallet/src/components/AppText.tsx
  apps/mobile-wallet/src/components/AssetAmountWithLogo.tsx
  apps/mobile-wallet/src/components/BalanceSummary.tsx
  apps/mobile-wallet/src/features/assetsDisplay/tokenDisplay/tokenDetailsModal/TokenDetailsModalBalanceSummary.tsx
Labels: 📱 MW

#1167 Add navigation buttons in ecosystem dApp WebView
  apps/mobile-wallet/src/features/ecosystem/DAppWebViewScreen.tsx
  apps/mobile-wallet/src/features/ecosystem/DAppsList.tsx
  apps/mobile-wallet/src/features/ecosystem/DAppsTags.tsx
  apps/mobile-wallet/src/features/ecosystem/EcosystemScreen.tsx
Labels: 📱 MW

#1184 Tweaks and fixes
  apps/mobile-wallet/locales/en-US/translation.json
  apps/mobile-wallet/src/components/AddressesTokensList.tsx
  apps/mobile-wallet/src/components/EmptyPlaceholder.tsx
  apps/mobile-wallet/src/components/NFTsGrid.tsx
  apps/mobile-wallet/src/components/TokenListItem.tsx
  apps/mobile-wallet/src/components/buttons/QuickActionButton.tsx
  apps/mobile-wallet/src/components/layout/TransactionsFlashList.tsx
  apps/mobile-wallet/src/features/addressesManagement/AddressDetailsModal.tsx
  apps/mobile-wallet/src/features/addressesManagement/AddressQuickActionsModal.tsx
  apps/mobile-wallet/src/features/assetsDisplay/hideAssets/HiddenAssetsScreen.tsx
  apps/mobile-wallet/src/features/assetsDisplay/hideAssets/SelectAssetToHideModal.tsx
  apps/mobile-wallet/src/features/assetsDisplay/tokenDisplay/TokenQuickActionsModal.tsx
  apps/mobile-wallet/src/features/ecosystem/DAppsList.tsx
  apps/mobile-wallet/src/features/ecosystem/EcosystemScreen.tsx
  apps/mobile-wallet/src/features/send/screens/AssetsScreen/AssetRow.tsx
  apps/mobile-wallet/src/modals/AddressPickerQuickActionsModal.tsx
  apps/mobile-wallet/src/navigation/InWalletNavigation.tsx
  apps/mobile-wallet/src/screens/Addresses/AddressesScreen.tsx
  apps/mobile-wallet/src/screens/Addresses/Contact/ContactScreen.tsx
  apps/mobile-wallet/src/screens/ContactListScreenBase.tsx
  apps/mobile-wallet/src/screens/Dashboard/DashboardScreen.tsx
  apps/mobile-wallet/src/style/themes.ts
Labels: 📱 MW

#1073 Add Thai Baht and Hong Kong Dollar
  .changeset/calm-hairs-rescue.md
  .changeset/eighty-squids-drive.md
  packages/shared/src/currencies.ts
  packages/shared/src/types/currencies.ts
Labels: 📱 MW, 🖥 DW

#1191 Eco mika
  apps/mobile-wallet/src/components/SearchInput.tsx
  apps/mobile-wallet/src/features/ecosystem/DAppCard.tsx
  apps/mobile-wallet/src/features/ecosystem/DAppsList.tsx
  apps/mobile-wallet/src/features/ecosystem/DAppsTags.tsx
  apps/mobile-wallet/src/features/ecosystem/EcosystemScreen.tsx
Labels: 📱 MW
