Repository alephium/alephium-frontend, pull requests merged in 2025-06, with the labels that each got.

#1352 Allow custom dApp URLs
  .changeset/sharp-wings-tell.md
  apps/mobile-wallet/locales/en-US/translation.json
  apps/mobile-wallet/src/components/inputs/Input.tsx
  apps/mobile-wallet/src/features/ecosystem/AddToFavoritesButton.tsx
  apps/mobile-wallet/src/features/ecosystem/DAppWebViewScreen.tsx
  apps/mobile-wallet/src/features/ecosystem/EditDappUrlModal.tsx
  apps/mobile-wallet/src/features/fund-password/FundPasswordModal.tsx
  apps/mobile-wallet/src/features/fund-password/FundPasswordScreen.tsx
  apps/mobile-wallet/src/features/modals/AppModals.tsx
  apps/mobile-wallet/src/features/modals/modalTypes.ts
  apps/mobile-wallet/src/features/send/screens/DestinationScreen.tsx
  apps/mobile-wallet/src/features/settings/EditWalletNameModal.tsx
  apps/mobile-wallet/src/features/settings/WalletDeleteModal.tsx
  apps/mobile-wallet/src/features/walletconnect/WalletConnectPasteUrlModal.tsx
  apps/mobile-wallet/src/screens/Addresses/Address/AddressForm.tsx
  apps/mobile-wallet/src/screens/Addresses/Contact/ContactFormBaseScreen.tsx
  apps/mobile-wallet/src/screens/CustomNetworkScreen.tsx
  apps/mobile-wallet/src/screens/new-wallet/DecryptScannedMnemonicScreen.tsx
  apps/mobile-wallet/src/screens/new-wallet/ImportWalletSeedScreen.tsx
  apps/mobile-wallet/src/screens/new-wallet/NewWalletNameScreen.tsx
  packages/shared/src/utils/utils.ts
  packages/shared/test/utils-test.ts
Labels: 📱 MW

#1346 Mobile fixes
  apps/mobile-wallet/ios/Podfile.lock
  apps/mobile-wallet/package.json
  apps/mobile-wallet/src/components/Amount.tsx
  apps/mobile-wallet/src/components/buttons/ActionCardButton.tsx
  apps/mobile-wallet/src/components/buttons/Button.tsx
  apps/mobile-wallet/src/components/headers/BaseHeader.tsx
  apps/mobile-wallet/src/contexts/HeaderContext.tsx
  apps/mobile-wallet/src/features/modals/BottomModal2.tsx
  apps/mobile-wallet/src/features/modals/BottomModalBackdrop.tsx
  apps/mobile-wallet/src/hooks/layout/useScreenScrollHandler.tsx
  apps/mobile-wallet/src/screens/Dashboard/DashboardSecondaryButtons.tsx
  apps/mobile-wallet/src/style/themes.ts
  pnpm-lock.yaml
Labels: 📱 MW

#1376 Redirect to 404 page if address isn't correct
  apps/explorer/src/pages/AddressInfoPage/index.tsx
Labels: 🔎 XPLR

#1373 Error indicators across wallets & error message modal
  .changeset/calm-vans-judge.md
  .changeset/curvy-colts-approve.md
  .changeset/fifty-eagles-sleep.md
  .changeset/sharp-wings-tell.md
  apps/desktop-wallet/package.json
  apps/desktop-wallet/src/features/transactionsDisplay/ActivityIndicator.tsx
  apps/desktop-wallet/src/pages/unlockedWallet/overviewPage/OverviewPage.tsx
  apps/desktop-wallet/src/pages/unlockedWallet/overviewPage/WalletWorth.tsx
  apps/mobile-wallet/CHANGELOG.md
  apps/mobile-wallet/android/app/build.gradle
  apps/mobile-wallet/app.config.js
  apps/mobile-wallet/ios/Alephium/Info.plist
  apps/mobile-wallet/locales/en-US/translation.json
  apps/mobile-wallet/package.json
  apps/mobile-wallet/src/components/BalanceSummary.tsx
  apps/mobile-wallet/src/features/modals/AppModals.tsx
  apps/mobile-wallet/src/features/modals/modalTypes.ts
  apps/mobile-wallet/src/modals/DataFetchErrorModal.tsx
  apps/mobile-wallet/src/screens/Dashboard/DashboardScreen.tsx
  package.json
  packages/shared-react/src/api/apiDataHooks/market/useFetchTokenPrices.ts
  packages/shared-react/src/api/apiDataHooks/utils/useFetchListedFtsWorth.ts
  packages/shared-react/src/api/apiDataHooks/wallet/useFetchWalletWorth.ts
  pnpm-lock.yaml
Labels: 📱 MW, 🖥 DW

#1379 Simplify modal dismissal
  apps/mobile-wallet/src/components/BiometricsWarningModal.tsx
  apps/mobile-wallet/src/components/ConsolidationModal.tsx
  apps/mobile-wallet/src/contexts/walletConnect/WalletConnectContext.tsx
  apps/mobile-wallet/src/contexts/walletConnect/WalletConnectSessionProposalModal.tsx
  apps/mobile-wallet/src/features/addressesManagement/AddressDetailsModal.tsx
  apps/mobile-wallet/src/features/addressesManagement/AddressNftsGridModal.tsx
  apps/mobile-wallet/src/features/addressesManagement/AddressQuickActionsModal.tsx
  apps/mobile-wallet/src/features/addressesManagement/AddressSettingsModal.tsx
  apps/mobile-wallet/src/features/assetsDisplay/hideTokens/SelectTokenToHideModal.tsx
  apps/mobile-wallet/src/features/assetsDisplay/nftsDisplay/NftGridModal.tsx
  apps/mobile-wallet/src/features/assetsDisplay/nftsDisplay/NftModal.tsx
  apps/mobile-wallet/src/features/assetsDisplay/tokenDisplay/TokenQuickActionsModal.tsx
  apps/mobile-wallet/src/features/assetsDisplay/tokenDisplay/tokenDetailsModal/AddressesWithTokenModal.tsx
  apps/mobile-wallet/src/features/assetsDisplay/tokenDisplay/tokenDetailsModal/TokenDetailsModal.tsx
  apps/mobile-wallet/src/features/auto-lock/AutoLockOptionsModal.tsx
  apps/mobile-wallet/src/features/backup/BackupReminderModal.tsx
  apps/mobile-wallet/src/features/buy/BuyModal.tsx
  apps/mobile-wallet/src/features/ecosystem/DAppDetailsModal.tsx
  apps/mobile-wallet/src/features/ecosystem/DAppQuickActionsModal.tsx
  apps/mobile-wallet/src/features/ecosystem/dAppMessaging/DappBrowserContext.tsx
  apps/mobile-wallet/src/features/ecosystem/modals/ConnectDappModal.tsx
  apps/mobile-wallet/src/features/ecosystem/modals/NetworkSwitchModal.tsx
  apps/mobile-wallet/src/features/ecosystem/modals/NewAddressModal.tsx
  apps/mobile-wallet/src/features/ecosystem/modals/SignDeployContractTxModal.tsx
  apps/mobile-wallet/src/features/ecosystem/modals/SignExecuteScriptTxModal.tsx
  apps/mobile-wallet/src/features/ecosystem/modals/SignMessageTxModal.tsx
  apps/mobile-wallet/src/features/ecosystem/modals/SignTransferTxModal.tsx
  apps/mobile-wallet/src/features/ecosystem/modals/SignTxModalTypes.ts
  apps/mobile-wallet/src/features/ecosystem/modals/SignUnsignedTxModal.tsx
  apps/mobile-wallet/src/features/ecosystem/modals/useSignModal.ts
  apps/mobile-wallet/src/features/fund-password/FundPasswordModal.tsx
  apps/mobile-wallet/src/features/localization/LanguageSelectModal.tsx
  apps/mobile-wallet/src/features/modals/AppModals.tsx
  apps/mobile-wallet/src/features/modals/BottomModal.tsx
  apps/mobile-wallet/src/features/modals/BottomModal2.tsx
  apps/mobile-wallet/src/features/modals/BottomModalBase.tsx
  apps/mobile-wallet/src/features/modals/BottomModalFlashList.tsx
  apps/mobile-wallet/src/features/modals/ModalContext.tsx
  apps/mobile-wallet/src/features/modals/modalTypes.ts
  apps/mobile-wallet/src/features/modals/useModalDismiss.ts
  apps/mobile-wallet/src/features/modals/withModal.tsx
  apps/mobile-wallet/src/features/qrCodeScan/AddressQRCodeScanActionsModal.tsx
  apps/mobile-wallet/src/features/receive/ReceiveQRCodeModal.tsx
  apps/mobile-wallet/src/features/send/modals/SelectAddressModal.tsx
  apps/mobile-wallet/src/features/send/modals/SelectContactModal.tsx
  apps/mobile-wallet/src/features/send/modals/TokenAmountModal.tsx
  apps/mobile-wallet/src/features/settings/CurrencySelectModal.tsx
  apps/mobile-wallet/src/features/settings/EditWalletNameModal.tsx
  apps/mobile-wallet/src/features/settings/MnemonicModal.tsx
  apps/mobile-wallet/src/features/settings/SafePlaceWarningModal.tsx
  apps/mobile-wallet/src/features/settings/WalletDeleteModal.tsx
  apps/mobile-wallet/src/features/settings/regionSettings/RegionSelectModal.tsx
  apps/mobile-wallet/src/features/transactionsDisplay/TransactionModal.tsx
  apps/mobile-wallet/src/features/walletconnect/WalletConnectErrorModal.tsx
  apps/mobile-wallet/src/features/walletconnect/WalletConnectPairingsModal.tsx
  apps/mobile-wallet/src/features/walletconnect/WalletConnectPasteUrlModal.tsx
  apps/mobile-wallet/src/modals/AddressPickerQuickActionsModal.tsx
  apps/mobile-wallet/src/modals/UnknownTokensModal.tsx
  apps/mobile-wallet/src/screens/Addresses/Address/GroupSelectModal.tsx
  apps/mobile-wallet/src/screens/SwitchNetworkModal.tsx
Labels: 📱 MW

#1382 Manage authorizations
  apps/mobile-wallet/locales/en-US/translation.json
  apps/mobile-wallet/src/components/EmptyPlaceholder.tsx
  apps/mobile-wallet/src/components/layout/FlashListScreen.tsx
  apps/mobile-wallet/src/features/ecosystem/DAppWebViewScreen.tsx
  apps/mobile-wallet/src/features/ecosystem/authorizedConnections/AuthorizedConnectionsEmptyList.tsx
  apps/mobile-wallet/src/features/ecosystem/authorizedConnections/AuthorizedConnectionsScreen.tsx
  apps/mobile-wallet/src/features/ecosystem/authorizedConnections/authorizedConnectionsAdapter.ts
  apps/mobile-wallet/src/features/ecosystem/authorizedConnections/authorizedConnectionsSlice.ts
  apps/mobile-wallet/src/features/ecosystem/authorizedConnections/authorizedConnectionsTypes.ts
  apps/mobile-wallet/src/features/ecosystem/authorizedConnections/persistedAuthorizedConnectionsStorage.ts
  apps/mobile-wallet/src/features/ecosystem/dAppMessaging/DappBrowserContext.tsx
  apps/mobile-wallet/src/features/ecosystem/dAppMessaging/dAppMessagingTypes.ts
  apps/mobile-wallet/src/features/ecosystem/dAppMessaging/dAppMessagingUtils.ts
  apps/mobile-wallet/src/features/ecosystem/modals/ConnectDappModal.tsx
  apps/mobile-wallet/src/features/settings/settingsScreen/SettingsDappsSection.tsx
  apps/mobile-wallet/src/features/settings/settingsScreen/SettingsScreen.tsx
  apps/mobile-wallet/src/features/walletconnect/WalletConnectPairingsModal.tsx
  apps/mobile-wallet/src/navigation/RootStackNavigation.tsx
  apps/mobile-wallet/src/navigation/rootStackRoutes.ts
Labels: 📱 MW

#1386 DApp Connect tip
  apps/mobile-wallet/locales/en-US/translation.json
  apps/mobile-wallet/src/features/connectTip/ConnectTipModal.tsx
  apps/mobile-wallet/src/features/connectTip/connectTipStorage.ts
  apps/mobile-wallet/src/features/ecosystem/dAppMessaging/DappBrowserContext.tsx
  apps/mobile-wallet/src/features/ecosystem/dAppMessaging/injectedJs.ts
  apps/mobile-wallet/src/features/modals/AppModals.tsx
  apps/mobile-wallet/src/features/modals/modalTypes.ts
Labels: 📱 MW

#1387 Fix loading animations
  apps/mobile-wallet/locales/en-US/translation.json
  apps/mobile-wallet/src/features/ecosystem/modals/NetworkSwitchModal.tsx
  apps/mobile-wallet/src/features/loader/LoadingManager.tsx
  apps/mobile-wallet/src/features/loader/SpinnerModal.tsx
  apps/mobile-wallet/src/features/loader/loaderActions.ts
  apps/mobile-wallet/src/features/loader/loaderSlice.ts
  apps/mobile-wallet/src/features/loader/loaderTypes.ts
  apps/mobile-wallet/src/screens/SwitchNetworkModal.tsx
Labels: 📱 MW

#1388 UI tweaks
  .changeset/fresh-spies-love.md
  apps/mobile-wallet/ios/Podfile.lock
  apps/mobile-wallet/package.json
  apps/mobile-wallet/src/components/BalanceSummary.tsx
  apps/mobile-wallet/src/components/RoundedCard.tsx
  apps/mobile-wallet/src/components/animatedBackground/AnimatedBackground.tsx
  apps/mobile-wallet/src/components/animatedBackground/ScreenAnimatedBackground.tsx
  apps/mobile-wallet/src/components/buttons/ActionCardButton.tsx
  apps/mobile-wallet/src/components/buttons/BottomButtons.tsx
  apps/mobile-wallet/src/components/footers/FooterMenu.tsx
  apps/mobile-wallet/src/components/headers/BaseHeader.tsx
  apps/mobile-wallet/src/features/assetsDisplay/tokenDisplay/tokenDetailsModal/TokenDetailsModal.tsx
  apps/mobile-wallet/src/features/backup/BackupReminderModal.tsx
  apps/mobile-wallet/src/features/buy/BuyModal.tsx
  apps/mobile-wallet/src/features/modals/BottomModal2.tsx
  apps/mobile-wallet/src/features/qrCodeScan/CameraScanButtonBase.tsx
  apps/mobile-wallet/src/screens/Dashboard/DashboardScreen.tsx
  apps/mobile-wallet/src/screens/Dashboard/DashboardSecondaryButtons.tsx
  apps/mobile-wallet/src/screens/LandingScreen.tsx
  apps/mobile-wallet/src/style/style.d.ts
  apps/mobile-wallet/src/style/themes.ts
  apps/mobile-wallet/src/utils/navigation.ts
  pnpm-lock.yaml
Labels: 📱 MW

#1393 Allow bg animations in top modal + more versatile focus detection
  apps/mobile-wallet/src/features/modals/BottomModal2.tsx
  apps/mobile-wallet/src/features/modals/ModalContext.tsx
  apps/mobile-wallet/src/features/modals/modalSelectors.ts
  apps/mobile-wallet/src/features/modals/useIsTopModal.tsx
  apps/mobile-wallet/src/screens/SwitchNetworkModal.tsx
  apps/mobile-wallet/src/utils/navigation.ts
Labels: 📱 MW

#1397 Fix scan modal opening, dry up useScreenOrModaIsFocused
  apps/mobile-wallet/src/components/animatedBackground/AnimatedBackground.tsx
  apps/mobile-wallet/src/features/qrCodeScan/CameraScanButtonBase.tsx
  apps/mobile-wallet/src/utils/navigation.ts
Labels: 📱 MW
