Repository alephium/alephium-frontend, pull requests merged in 2025-05, with the labels that each got.

#1334 Explorer refresh 0525
  apps/explorer/src/components/AppFooter.tsx
  apps/explorer/src/components/Cards/Card.tsx
  apps/explorer/src/components/Cards/StatisticTextual.tsx
  apps/explorer/src/components/Charts/NakedChart.tsx
  apps/explorer/src/components/SectionTitle.tsx
  apps/explorer/src/components/Table/Table.tsx
  apps/explorer/src/components/Table/TableHeader.tsx
  apps/explorer/src/components/Table/TableRow.tsx
  apps/explorer/src/components/Table/TableTabBar.tsx
  apps/explorer/src/components/Timestamp.tsx
  apps/explorer/src/components/Wave/WaveEntity.ts
  apps/explorer/src/components/Wave/Waves.tsx
  apps/explorer/src/fonts/Geist-Variable.ttf
  apps/explorer/src/fonts/Inter-Bold.woff
  apps/explorer/src/fonts/Inter-Medium.woff
  apps/explorer/src/fonts/Inter-Regular.woff
  apps/explorer/src/fonts/Inter-SemiBold.woff
  apps/explorer/src/fonts/InterDisplay-Bold.woff2
  apps/explorer/src/fonts/InterDisplay-Light.woff2
  apps/explorer/src/fonts/InterDisplay-Medium.woff2
  apps/explorer/src/fonts/InterDisplay-Regular.woff2
  apps/explorer/src/fonts/InterDisplay-SemiBold.woff2
  apps/explorer/src/fonts/InterDisplay-Thin.woff2
  apps/explorer/src/fonts/index.css
  apps/explorer/src/pages/AddressInfoPage/NFTList.tsx
  apps/explorer/src/pages/HomePage/HomePage.tsx
  apps/explorer/src/pages/HomePage/useBlockListData.ts
  apps/explorer/src/styles/globalStyles.ts
  apps/explorer/src/styles/themes.ts
Labels: 🔎 XPLR

#1331 Tanstack & Expo [7/8]: Enable new architecture
  apps/mobile-wallet/android/gradle.properties
  apps/mobile-wallet/app.config.js
  apps/mobile-wallet/ios/Alephium.xcodeproj/project.pbxproj
  apps/mobile-wallet/ios/Podfile.lock
  apps/mobile-wallet/ios/Podfile.properties.json
  apps/mobile-wallet/src/components/layout/ScrollScreen.tsx
Labels: 📱 MW

#1332 Tanstack & Expo [8/8]: Replace AsyncStorage with MMKV
  apps/mobile-wallet/__tests__/wallet.test.ts
  apps/mobile-wallet/ios/Podfile.lock
  apps/mobile-wallet/package.json
  apps/mobile-wallet/src/App.tsx
  apps/mobile-wallet/src/features/assetsDisplay/hideTokens/hiddenTokensStorage.ts
  apps/mobile-wallet/src/features/ecosystem/favoriteDAppsStorage.ts
  apps/mobile-wallet/src/features/settings/settingsScreen/SettingsDevSection.tsx
  apps/mobile-wallet/src/features/settings/useLoadStoredSettings.ts
  apps/mobile-wallet/src/persistent-storage/app.ts
  apps/mobile-wallet/src/persistent-storage/storage.ts
  apps/mobile-wallet/src/persistent-storage/tanstackAsyncStoragePersister.ts
  apps/mobile-wallet/src/persistent-storage/utils.ts
  apps/mobile-wallet/src/persistent-storage/wallet.ts
  apps/mobile-wallet/src/screens/Dashboard/DashboardScreen.tsx
  pnpm-lock.yaml
Labels: 📱 MW

#1341 Compactify layout
  .changeset/real-showers-sin.md
  apps/explorer/src/components/AppFooter.tsx
  apps/explorer/src/components/AppHeader.tsx
  apps/explorer/src/components/Cards/Card.tsx
  apps/explorer/src/components/Charts/LineAreaChart.tsx
  apps/explorer/src/components/Menu.tsx
  apps/explorer/src/components/NetworkLogo.tsx
  apps/explorer/src/components/SectionTitle.tsx
  apps/explorer/src/components/Select.tsx
  apps/explorer/src/components/Table/Table.tsx
  apps/explorer/src/components/Table/TableRow.tsx
  apps/explorer/src/components/ThemeSwitcher.tsx
  apps/explorer/src/pages/AddressInfoPage/AddressTransactionRow.tsx
  apps/explorer/src/pages/BlockInfoPage.tsx
  apps/explorer/src/styles/themes.ts
Labels: 🔎 XPLR

#1322 Fix tx caching and add activity indicator
  .changeset/fruity-bars-sniff.md
  .changeset/warm-geckos-cheer.md
  apps/desktop-wallet/src/features/transactionsDisplay/ActivityIndicator.tsx
  apps/desktop-wallet/src/pages/unlockedWallet/UnlockedWalletLayout.tsx
  packages/shared-react/src/api/queries/transactionQueries.ts
  packages/shared-react/src/hooks/index.ts
  packages/shared-react/src/hooks/useActivityIndicator.ts
Labels: 🖥 DW

#1344 Support displaying groupless addresses
  .changeset/tasty-meals-strive.md
  apps/explorer/locales/en-US/translation.json
  apps/explorer/src/components/AppHeader.tsx
  apps/explorer/src/components/Buttons/Button.tsx
  apps/explorer/src/components/Cards/Card.tsx
  apps/explorer/src/components/Cards/StatisticTextual.tsx
  apps/explorer/src/components/HighlightedHash.tsx
  apps/explorer/src/components/Links.tsx
  apps/explorer/src/components/Menu.tsx
  apps/explorer/src/components/NetworkSwitch.tsx
  apps/explorer/src/components/PageSwitch.tsx
  apps/explorer/src/components/SearchBar.tsx
  apps/explorer/src/components/SectionTitle.tsx
  apps/explorer/src/components/Table/Table.tsx
  apps/explorer/src/components/Table/TableDetailsRow.tsx
  apps/explorer/src/components/Table/TableHeader.tsx
  apps/explorer/src/components/Table/TableRow.tsx
  apps/explorer/src/components/Table/TableTabBar.tsx
  apps/explorer/src/components/Wave/WaveEntity.ts
  apps/explorer/src/features/localization/LanguageSwitch.tsx
  apps/explorer/src/pages/AddressInfoPage/AddressTransactionRow.tsx
  apps/explorer/src/pages/AddressInfoPage/AssetList.tsx
  apps/explorer/src/pages/AddressInfoPage/InfoGrid.tsx
  apps/explorer/src/pages/AddressInfoPage/NFTDetailsModal.tsx
  apps/explorer/src/pages/AddressInfoPage/TokenList.tsx
  apps/explorer/src/pages/AddressInfoPage/index.tsx
  apps/explorer/src/pages/BlockInfoPage.tsx
  apps/explorer/src/pages/HomePage/HomePage.tsx
  apps/explorer/src/pages/TransactionInfoPage.tsx
  apps/explorer/src/styles/themes.ts
Labels: 🔎 XPLR
