Repository alephium/alephium-frontend, pull requests merged in 2025-02, with the labels that each got.

#1210 Post eco fixes
  .changeset/cold-donuts-film.md
  .changeset/hip-eyes-lay.md
  .changeset/ten-papayas-heal.md
  apps/mobile-wallet/ios/Podfile.lock
  apps/mobile-wallet/locales/en-US/translation.json
  apps/mobile-wallet/src/components/buttons/QuickActionButton.tsx
  apps/mobile-wallet/src/contexts/walletConnect/WalletConnectContext.tsx
  apps/mobile-wallet/src/contexts/walletConnect/WalletConnectSessionProposalModal.tsx
  apps/mobile-wallet/src/contexts/walletConnect/WalletConnectSessionRequestModal.tsx
  apps/mobile-wallet/src/contexts/walletConnect/useWalletConnectToasts.ts
  apps/mobile-wallet/src/features/assetsDisplay/tokenDisplay/tokenDetailsModal/TokenDetailsModal.tsx
  apps/mobile-wallet/src/features/buy/BuyModal.tsx
  apps/mobile-wallet/src/features/ecosystem/DAppDetailsModal.tsx
  apps/mobile-wallet/src/features/ecosystem/DAppQuickActionsModal.tsx
  apps/mobile-wallet/src/features/ecosystem/DAppWebViewScreen.tsx
  apps/mobile-wallet/src/features/ecosystem/VisitDAppButton.tsx
  apps/mobile-wallet/tsconfig.json
Labels: 📱 MW

#1219 Don't show close button in modals with non-scrollable content
  .changeset/pretty-ducks-fly.md
  apps/mobile-wallet/src/features/modals/BottomModalBase.tsx
  apps/mobile-wallet/src/features/modals/BottomModalHeader.tsx
Labels: 📱 MW

#1197 Region settings
  .changeset/tall-foxes-eat.md
  .changeset/wild-jobs-train.md
  apps/desktop-wallet/src/App.tsx
  apps/desktop-wallet/src/features/analytics/useTrackUserSettings.ts
  apps/desktop-wallet/src/features/settings/RegionSettings.tsx
  apps/desktop-wallet/src/features/settings/regionSettings/regions.json
  apps/desktop-wallet/src/features/settings/regionSettings/useRegionOptions.ts
  apps/mobile-wallet/locales/en-US/translation.json
  apps/mobile-wallet/src/App.tsx
  apps/mobile-wallet/src/components/Amount.tsx
  apps/mobile-wallet/src/components/ConsolidationModal.tsx
  apps/mobile-wallet/src/features/modals/AppModals.tsx
  apps/mobile-wallet/src/features/modals/modalTypes.ts
  apps/mobile-wallet/src/features/settings/regionSettings/RegionSelectModal.tsx
  apps/mobile-wallet/src/features/settings/regionSettings/RegionSettingsRow.tsx
  apps/mobile-wallet/src/features/settings/regionSettings/regionSettingsActions.ts
  apps/mobile-wallet/src/features/settings/regionSettings/regions.json
  apps/mobile-wallet/src/features/settings/regionSettings/regionsUtils.ts
  apps/mobile-wallet/src/features/settings/regionSettings/useSystemRegion.ts
  apps/mobile-wallet/src/features/settings/settingsPersistentStorage.ts
  apps/mobile-wallet/src/features/settings/settingsScreen/SettingsScreen.tsx
  apps/mobile-wallet/src/features/settings/settingsSlice.ts
  apps/mobile-wallet/src/features/transactionsDisplay/TransactionModal.tsx
  apps/mobile-wallet/src/screens/AddressDiscoveryScreen.tsx
  apps/mobile-wallet/src/types/settings.ts
Labels: 📱 MW

#1187 Feat address ordering
  apps/desktop-wallet/locales/en-US/translation.json
  apps/desktop-wallet/src/features/addressDeletion/DeleteAddressesModal.tsx
  apps/desktop-wallet/src/features/addressFiltering/addressFilteringHooks.tsx
  apps/desktop-wallet/src/features/send/AddressInputs.tsx
  apps/desktop-wallet/src/features/send/sendModals/callContract/AddressesTxModalContent.tsx
  apps/desktop-wallet/src/features/settings/settingsActions.ts
  apps/desktop-wallet/src/features/settings/settingsConstants.ts
  apps/desktop-wallet/src/features/settings/settingsSlice.ts
  apps/desktop-wallet/src/features/settings/settingsTypes.ts
  apps/desktop-wallet/src/hooks/useAddresses.ts
  apps/desktop-wallet/src/modals/AddressSelectModal.tsx
  apps/desktop-wallet/src/modals/AddressSweepModal.tsx
  apps/desktop-wallet/src/modals/ReceiveModal.tsx
  apps/desktop-wallet/src/pages/UnlockedWallet/AddressesPage/AddressSortingSelect.tsx
  apps/desktop-wallet/src/pages/UnlockedWallet/AddressesPage/AddressesTabContent.tsx
  apps/desktop-wallet/src/pages/UnlockedWallet/OverviewPage/AddressesList.tsx
  apps/desktop-wallet/src/tests/settings.test.ts
  apps/desktop-wallet/src/utils/addresses.ts
Labels: 🖥 DW, ALPH-800

#1198 Display tx and fee worth before sending
  .changeset/green-tools-beg.md
  apps/mobile-wallet/locales/en-US/translation.json
  apps/mobile-wallet/src/components/Amount.tsx
  apps/mobile-wallet/src/components/AssetAmountWithLogo.tsx
  apps/mobile-wallet/src/contexts/walletConnect/WalletConnectSessionRequestModal.tsx
  apps/mobile-wallet/src/features/send/screens/FeeAmounts.tsx
  apps/mobile-wallet/src/features/send/screens/TotalWorthRow.tsx
  apps/mobile-wallet/src/features/send/screens/VerifyScreen.tsx
Labels: 📱 MW

#1244 Searchable flashlists mika
  apps/mobile-wallet/src/components/BiometricsWarningModal.tsx
  apps/mobile-wallet/src/components/RadioButtonRow.tsx
  apps/mobile-wallet/src/components/SearchInput.tsx
  apps/mobile-wallet/src/components/buttons/Button.tsx
  apps/mobile-wallet/src/components/inputs/Input.tsx
  apps/mobile-wallet/src/features/modals/BottomModal.tsx
  apps/mobile-wallet/src/features/modals/BottomModalBase.tsx
  apps/mobile-wallet/src/features/modals/BottomModalFlashList.tsx
  apps/mobile-wallet/src/features/modals/BottomModalHeader.tsx
Labels: 📱 MW

#1250 Use flashlist for addresses list in addresses screen
  apps/mobile-wallet/src/screens/Addresses/AddressesScreen.tsx
Labels: 📱 MW

#1248 Display entered amount fiat worth
  .changeset/warm-schools-jog.md
  apps/mobile-wallet/src/components/Amount.tsx
  apps/mobile-wallet/src/features/send/modals/TokenAmountModal.tsx
Labels: 📱 MW

#1222 Add bg to NFT thumbnails
  apps/mobile-wallet/src/components/NFTImage.tsx
Labels: 📱 MW

#1232 Group NFTs per collection
  .changeset/curvy-timers-jump.md
  apps/desktop-wallet/src/api/apiDataHooks/address/useFetchAddressBalancesAlph.ts
  apps/desktop-wallet/src/api/apiDataHooks/address/useFetchAddressBalancesTokens.ts
  apps/desktop-wallet/src/api/apiDataHooks/address/useFetchAddressInfiniteTransactions.ts
  apps/desktop-wallet/src/api/apiDataHooks/address/useFetchAddressLatestTransaction.ts
  apps/desktop-wallet/src/api/apiDataHooks/address/useFetchAddressSingleTokenBalances.ts
  apps/desktop-wallet/src/api/apiDataHooks/market/useFetchTokenPrices.ts
  apps/desktop-wallet/src/api/apiDataHooks/token/useFetchNft.ts
  apps/desktop-wallet/src/api/apiDataHooks/token/useFetchToken.ts
  apps/desktop-wallet/src/api/apiDataHooks/transaction/useFetchPendingTransaction.ts
  apps/desktop-wallet/src/api/apiDataHooks/transaction/useFetchTransaction.ts
  apps/desktop-wallet/src/api/apiDataHooks/utils/useFetchFtList.ts
  apps/desktop-wallet/src/api/apiDataHooks/utils/useFetchSortedFts.ts
  apps/desktop-wallet/src/api/apiDataHooks/utils/useFetchTokensSeparatedByType.ts
  apps/desktop-wallet/src/api/apiDataHooks/utils/useFetchWalletBalancesAlph.ts
  apps/desktop-wallet/src/api/apiDataHooks/utils/useFetchWalletBalancesTokens.ts
  apps/desktop-wallet/src/api/apiDataHooks/wallet/useFetchLatestTransactionOfEachAddress.ts
  apps/desktop-wallet/src/api/apiDataHooks/wallet/useFetchWalletNftsSearchStrings.ts
  apps/desktop-wallet/src/api/apiDataHooks/wallet/useFetchWalletSingleTokenBalances.ts
  apps/desktop-wallet/src/api/apiDataHooks/wallet/useFetchWalletTransactionsInfinite.ts
  apps/desktop-wallet/src/api/apiDataHooks/wallet/useFetchWalletTransactionsLimited.tsx
  apps/desktop-wallet/src/api/queries/addressQueries.ts
  apps/desktop-wallet/src/api/queries/priceQueries.ts
  apps/desktop-wallet/src/api/queries/tokenQueries.ts
  apps/desktop-wallet/src/api/queries/transactionQueries.ts
  apps/desktop-wallet/src/components/Buttons/ShortcutButtons.tsx
  apps/desktop-wallet/src/features/dataPolling/useAddressesDataPolling.ts
  apps/desktop-wallet/src/features/dataPolling/usePendingTxPolling.ts
  apps/desktop-wallet/src/features/historicChart/useHistoricData.tsx
  apps/desktop-wallet/src/features/transactionsDisplay/useFetchTransactionTokens.ts
  apps/desktop-wallet/src/hooks/useAddresses.ts
  apps/desktop-wallet/src/modals/NFTDetailsModal.tsx
  apps/mobile-wallet/src/components/NFTsGrid.tsx
  apps/mobile-wallet/src/features/assetsDisplay/nftsDisplay/NftsCollectionTitle.tsx
  apps/mobile-wallet/src/screens/NFTs/NFTListScreen.tsx
  packages/shared-react/package.json
  packages/shared-react/src/api/apiDataHooks/index.ts
  packages/shared-react/src/api/apiDataHooks/useFetchNftCollection.ts
  packages/shared-react/src/api/apiUtils.ts
  packages/shared-react/src/api/index.ts
  packages/shared-react/src/index.tsx
  packages/shared-react/src/network/index.ts
  packages/shared-react/src/network/networkSelectors.ts
  packages/shared-react/src/network/useCurrentlyOnlineNetworkId.ts
  packages/shared-react/src/walletConnect/useWalletConnectNetworkSwitch.ts
  packages/shared/src/api/apiUtils.ts
  packages/shared/src/api/index.ts
  pnpm-lock.yaml
Labels: 📱 MW

#1247 Hide already entered words of imported mnemonic
  .changeset/tall-frogs-tickle.md
  apps/mobile-wallet/src/components/SecretPhraseWordList.tsx
  apps/mobile-wallet/src/features/backup/backupScreens/VerifyMnemonicScreen.tsx
Labels: 📱 MW

#1199 Update web3 packages from 1.5.1 to 1.11.3
  apps/desktop-wallet/package.json
  apps/desktop-wallet/src/features/send/SendModal.tsx
  apps/desktop-wallet/src/features/send/sendModals/callContract/CallContractSendModal.tsx
  apps/desktop-wallet/src/features/send/sendTypes.ts
  apps/explorer/package.json
  apps/explorer/src/api/assets/assetsHooks.ts
  apps/explorer/src/pages/AddressInfoPage/AssetList.tsx
  apps/mobile-wallet/package.json
  apps/mobile-wallet/src/contexts/SendContext.tsx
  apps/mobile-wallet/src/types/walletConnect.ts
  packages/keyring/package.json
  packages/shared-react/package.json
  packages/shared/package.json
  packages/shared/src/assets.ts
  pnpm-lock.yaml
Labels: 📱 MW, 🖥 DW, 🔎 XPLR

#1223 Video NFTs
  .changeset/grumpy-cycles-pay.md
  apps/mobile-wallet/android/app/src/main/AndroidManifest.xml
  apps/mobile-wallet/app.config.js
  apps/mobile-wallet/ios/Alephium/Info.plist
  apps/mobile-wallet/ios/Podfile.lock
  apps/mobile-wallet/package.json
  apps/mobile-wallet/src/components/NFTImage.tsx
  apps/mobile-wallet/src/components/NFTPlaceholder.tsx
  apps/mobile-wallet/src/components/nft/NftVideo.tsx
  apps/mobile-wallet/src/components/nft/NftVideoPlayIconOverlay.tsx
  apps/mobile-wallet/src/features/assetsDisplay/nftsDisplay/NftModal.tsx
  apps/mobile-wallet/src/features/assetsDisplay/nftsDisplay/useIsNftCached.ts
  apps/mobile-wallet/src/features/assetsDisplay/nftsDisplay/useNftHeaderData.ts
  apps/mobile-wallet/src/features/modals/modalSelectors.ts
  apps/mobile-wallet/src/style/style.d.ts
  apps/mobile-wallet/src/style/themes.ts
  pnpm-lock.yaml
Labels: 📱 MW

#1262 Improve DW v3 performance
  .changeset/perfect-chairs-peel.md
  apps/desktop-wallet/src/api/apiDataHooks/market/useFetchTokenPrices.ts
  apps/desktop-wallet/src/api/apiDataHooks/token/useFetchToken.ts
  apps/desktop-wallet/src/api/apiDataHooks/utils/useFetchFtList.ts
  apps/desktop-wallet/src/api/apiDataHooks/wallet/useFetchWalletBalancesAlphByAddress.ts
  apps/desktop-wallet/src/api/apiDataHooks/wallet/useFetchWalletBalancesByAddress.tsx
  apps/desktop-wallet/src/api/apiDataHooks/wallet/useFetchWalletBalancesTokensByAddress.ts
  apps/desktop-wallet/src/api/apiDataHooks/wallet/useFetchWalletFts.ts
  apps/desktop-wallet/src/api/apiDataHooks/wallet/useFetchWalletNftsSearchStrings.ts
  apps/desktop-wallet/src/api/apiDataHooks/wallet/useFetchWalletTokensByType.ts
  apps/desktop-wallet/src/api/apiDataHooks/wallet/useFetchWalletTokensByType.tsx
  apps/desktop-wallet/src/api/apiDataHooks/wallet/useFetchWalletWorthAlph.ts
  apps/desktop-wallet/src/api/context/apiContext.tsx
  apps/desktop-wallet/src/api/queries/addressQueries.ts
  apps/desktop-wallet/src/api/queries/tokenQueries.ts
  apps/desktop-wallet/src/components/Amount.tsx
  apps/desktop-wallet/src/components/AssetLogo.tsx
  apps/desktop-wallet/src/components/Inputs/SelectOptionTokenName.tsx
  apps/desktop-wallet/src/components/Inputs/SelectOptionWalletToken.tsx
  apps/desktop-wallet/src/components/NFTCard.tsx
  apps/desktop-wallet/src/components/TokenBadge.tsx
  apps/desktop-wallet/src/features/addressFiltering/addressFilteringHooks.tsx
  apps/desktop-wallet/src/features/assetsLists/AddressTokenBadge.tsx
  apps/desktop-wallet/src/features/assetsLists/AddressTokensBadgesList.tsx
  apps/desktop-wallet/src/features/assetsLists/FTsBalancesList.tsx
  apps/desktop-wallet/src/features/assetsLists/NFTsGrid.tsx
  apps/desktop-wallet/src/features/assetsLists/tokenBalanceRow/FTAllocationCell.tsx
  apps/desktop-wallet/src/features/assetsLists/tokenBalanceRow/FTWorthCell.tsx
  apps/desktop-wallet/src/features/send/CheckAmountsBox.tsx
  apps/desktop-wallet/src/features/send/SelectOptionAddressToken.tsx
  apps/desktop-wallet/src/features/theme/themes.ts
  apps/desktop-wallet/src/features/transactionsDisplay/useFetchTransactionTokens.ts
  apps/desktop-wallet/src/features/walletConnect/WalletConnectSessionRequestEventHandler.tsx
  apps/desktop-wallet/src/hooks/useAddresses.ts
  apps/desktop-wallet/src/modals/AddressSelectModal.tsx
  apps/desktop-wallet/src/pages/unlockedWallet/activityPage/FiltersPanel.tsx
  apps/desktop-wallet/src/types/tokens.ts
Labels: 🖥 DW

#1267 DW v3.0 fixes
  apps/desktop-wallet/locales/en-US/translation.json
  apps/desktop-wallet/src/App.tsx
  apps/desktop-wallet/src/components/AddressBadge.tsx
  apps/desktop-wallet/src/components/AddressColorIndicator.tsx
  apps/desktop-wallet/src/components/AddressMetadataForm.tsx
  apps/desktop-wallet/src/components/Amount.tsx
  apps/desktop-wallet/src/components/Buttons/ShortcutButtons.tsx
  apps/desktop-wallet/src/components/DataList.tsx
  apps/desktop-wallet/src/components/DefaultAddressSwitch.tsx
  apps/desktop-wallet/src/components/HashEllipsed.tsx
  apps/desktop-wallet/src/components/Inputs/ColoredLabelInput.tsx
  apps/desktop-wallet/src/components/Inputs/Select.tsx
  apps/desktop-wallet/src/components/LabeledWorthOverview.tsx
  apps/desktop-wallet/src/components/NavItem.tsx
  apps/desktop-wallet/src/components/PageComponents/SideBar.tsx
  apps/desktop-wallet/src/components/PageComponents/SideBarSettingsButton.tsx
  apps/desktop-wallet/src/components/PasswordConfirmation.tsx
  apps/desktop-wallet/src/components/Popup.tsx
  apps/desktop-wallet/src/components/Scrollbar.tsx
  apps/desktop-wallet/src/features/assetsLists/tokenBalanceRow/TokenLogo.tsx
  apps/desktop-wallet/src/features/passphrase/UsePassphraseButton.tsx
  apps/desktop-wallet/src/features/passphrase/usePassphrase.ts
  apps/desktop-wallet/src/features/send/CheckAddressesBox.tsx
  apps/desktop-wallet/src/features/send/CheckAmountsBox.tsx
  apps/desktop-wallet/src/features/send/InfoRow.tsx
  apps/desktop-wallet/src/features/send/SendModal.tsx
  apps/desktop-wallet/src/features/send/TokensAmountInputs.tsx
  apps/desktop-wallet/src/features/send/sendModals/transfer/BuildTxModalContent.tsx
  apps/desktop-wallet/src/features/send/sendModals/transfer/CheckTxModalContent.tsx
  apps/desktop-wallet/src/features/switch-wallet/WalletUnlockModal.tsx
  apps/desktop-wallet/src/features/transactionsDisplay/transactionDetailsModal/AddressesDataRows.tsx
  apps/desktop-wallet/src/features/transactionsDisplay/transactionDetailsModal/DirectionalInfo.tsx
  apps/desktop-wallet/src/features/transactionsDisplay/transactionDetailsModal/FTAmounts.tsx
  apps/desktop-wallet/src/features/transactionsDisplay/transactionDetailsModal/FTsDataListRow.tsx
  apps/desktop-wallet/src/features/transactionsDisplay/transactionDetailsModal/TransactionDetailsModal.tsx
  apps/desktop-wallet/src/features/transactionsDisplay/transactionDetailsModal/TransactionType.tsx
  apps/desktop-wallet/src/modals/AddressDetailsModal/AddressDetailsModalHeader.tsx
  apps/desktop-wallet/src/modals/AddressOptionsModal.tsx
  apps/desktop-wallet/src/modals/AppModals.tsx
  apps/desktop-wallet/src/modals/CenteredModal.tsx
  apps/desktop-wallet/src/modals/SideModal.tsx
  apps/desktop-wallet/src/modals/WalletQRCodeExportModal.tsx
  apps/desktop-wallet/src/modals/tokenDetails/TokenBalances.tsx
  apps/desktop-wallet/src/modals/tokenDetails/TokenDetailsModal.tsx
  apps/desktop-wallet/src/modals/tokenDetails/TokenDetailsModalHeader.tsx
  apps/desktop-wallet/src/pages/HomePage/UnlockPanel.tsx
  apps/desktop-wallet/src/pages/HomePage/index.tsx
  apps/desktop-wallet/src/pages/LockedWalletLayout.tsx
  apps/desktop-wallet/src/pages/unlockedWallet/UnlockedWalletLayout.tsx
  apps/desktop-wallet/src/pages/unlockedWallet/UnlockedWalletPage.tsx
  apps/desktop-wallet/src/pages/unlockedWallet/addressesPage/AddressSortingSelect.tsx
  apps/desktop-wallet/src/pages/unlockedWallet/addressesPage/AddressesPage.tsx
  apps/desktop-wallet/src/pages/unlockedWallet/addressesPage/addressListRow/AddressListRow.tsx
Labels: 🖥 DW

#1275 Stacked toasts
  .changeset/soft-jobs-sit.md
  apps/desktop-wallet/src/features/autoUpdate/AutoUpdateToastBox.tsx
  apps/desktop-wallet/src/features/buy/BuyModal.tsx
  apps/desktop-wallet/src/features/ledger/LedgerAddressDiscoveryToastBox.tsx
  apps/desktop-wallet/src/features/ledger/useLedger.ts
  apps/desktop-wallet/src/features/send/sentTransactions/SentTransactionToastBox.tsx
  apps/desktop-wallet/src/features/send/sentTransactions/SentTransactionsToastMessages.tsx
  apps/desktop-wallet/src/features/send/sentTransactions/sentTransactionsActions.ts
  apps/desktop-wallet/src/features/send/sentTransactions/sentTransactionsAdapter.ts
  apps/desktop-wallet/src/features/send/sentTransactions/sentTransactionsSlice.ts
  apps/desktop-wallet/src/features/toastMessages/StackedToasts.tsx
  apps/desktop-wallet/src/features/toastMessages/ToastBox.tsx
  apps/desktop-wallet/src/features/toastMessages/ToastMessages.tsx
  apps/desktop-wallet/src/features/toastMessages/ToastMessagesModal.tsx
  apps/desktop-wallet/src/features/toastMessages/toastMessagesActions.ts
  apps/desktop-wallet/src/features/toastMessages/toastMessagesAdapter.ts
  apps/desktop-wallet/src/features/toastMessages/toastMessagesSelectors.ts
  apps/desktop-wallet/src/features/toastMessages/toastMessagesSlice.ts
  apps/desktop-wallet/src/features/toastMessages/toastMessagesTypes.ts
  apps/desktop-wallet/src/features/walletConnect/WalletConnectSessionProposalModal.tsx
  apps/desktop-wallet/src/hooks/useAddressGeneration.tsx
  apps/desktop-wallet/src/modals/NewAddressModal.tsx
  apps/desktop-wallet/src/storage/addresses/addressesActions.ts
  apps/desktop-wallet/src/storage/dApps/dAppActions.ts
  apps/desktop-wallet/src/storage/global/globalActions.ts
  apps/desktop-wallet/src/storage/transactions/transactionsActions.ts
  apps/desktop-wallet/src/storage/wallets/walletActions.ts
Labels: 🖥 DW

#1276 Dw redesign fixes windows
  apps/desktop-wallet/src/components/AppHeader.tsx
  apps/desktop-wallet/src/components/Box.tsx
  apps/desktop-wallet/src/components/PageComponents/SideBar.tsx
  apps/desktop-wallet/src/components/Popup.tsx
  apps/desktop-wallet/src/components/TitleBar.tsx
  apps/desktop-wallet/src/features/addressDeletion/DeleteAddressesModal.tsx
  apps/desktop-wallet/src/features/buy/BuyModal.tsx
  apps/desktop-wallet/src/features/passphrase/WalletPassphraseDisclaimerModal.tsx
  apps/desktop-wallet/src/features/send/CheckAddressesBox.tsx
  apps/desktop-wallet/src/features/send/CheckAmountsBox.tsx
  apps/desktop-wallet/src/features/send/SendModal.tsx
  apps/desktop-wallet/src/features/send/sendModals/callContract/CheckTxModalContent.tsx
  apps/desktop-wallet/src/features/send/sendModals/deployContract/CheckTxModalContent.tsx
  apps/desktop-wallet/src/features/send/sendModals/transfer/CheckTxModalContent.tsx
  apps/desktop-wallet/src/features/send/sendModals/transfer/ConfirmLockTimeModal.tsx
  apps/desktop-wallet/src/features/switch-wallet/WalletUnlockModal.tsx
  apps/desktop-wallet/src/features/theme/themes.ts
  apps/desktop-wallet/src/features/walletConnect/SignMessageModal.tsx
  apps/desktop-wallet/src/features/walletConnect/SignUnsignedTxModal.tsx
  apps/desktop-wallet/src/features/walletConnect/WalletConnectModal.tsx
  apps/desktop-wallet/src/features/walletConnect/WalletConnectSessionProposalModal.tsx
  apps/desktop-wallet/src/features/walletExport/qrCodeExport/WalletQRCodeExportModal.tsx
  apps/desktop-wallet/src/features/walletExport/secretPhraseExport/SecretPhraseModal.tsx
  apps/desktop-wallet/src/modals/AddressOptionsModal.tsx
  apps/desktop-wallet/src/modals/AddressSweepModal.tsx
  apps/desktop-wallet/src/modals/CSVExportModal.tsx
  apps/desktop-wallet/src/modals/CenteredModal.tsx
  apps/desktop-wallet/src/modals/ConfirmModal.tsx
  apps/desktop-wallet/src/modals/ConsolidateUTXOsModal.tsx
  apps/desktop-wallet/src/modals/ContactFormModal.tsx
  apps/desktop-wallet/src/modals/NewAddressModal.tsx
  apps/desktop-wallet/src/modals/SettingsModal/CopyPrivateKeyConfirmationModal.tsx
  apps/desktop-wallet/src/modals/SettingsModal/DisablePasswordRequirementModal.tsx
  apps/desktop-wallet/src/modals/SettingsModal/EditWalletNameModal.tsx
  apps/desktop-wallet/src/modals/WalletRemovalModal.tsx
  apps/desktop-wallet/src/pages/LockedWalletLayout.tsx
  apps/desktop-wallet/src/pages/unlockedWallet/UnlockedWalletLayout.tsx
  apps/desktop-wallet/src/style/globalStyles.ts
Labels: 🖥 DW

#1274 Update toasts
  .changeset/soft-jobs-sit.md
  apps/desktop-wallet/src/App.tsx
  apps/desktop-wallet/src/components/SnackbarManager.tsx
  apps/desktop-wallet/src/features/autoUpdate/AutoUpdateToastBox.tsx
  apps/desktop-wallet/src/features/autoUpdate/AutoUpdateToastMessages.tsx
  apps/desktop-wallet/src/features/buy/BuyModal.tsx
  apps/desktop-wallet/src/features/buy/useOnramperUrl.ts
  apps/desktop-wallet/src/features/ledger/LedgerAddressDiscoverySnackbar.tsx
  apps/desktop-wallet/src/features/ledger/LedgerAddressDiscoveryToastBox.tsx
  apps/desktop-wallet/src/features/ledger/LedgerToastMessages.tsx
  apps/desktop-wallet/src/features/ledger/useLedger.ts
  apps/desktop-wallet/src/features/send/sentTransactions/SentTransactionToastBox.tsx
  apps/desktop-wallet/src/features/send/sentTransactions/SentTransactionsToastMessages.tsx
  apps/desktop-wallet/src/features/send/sentTransactions/sentTransactionsActions.ts
  apps/desktop-wallet/src/features/send/sentTransactions/sentTransactionsAdapter.ts
  apps/desktop-wallet/src/features/send/sentTransactions/sentTransactionsSlice.ts
  apps/desktop-wallet/src/features/snackbar/SnackbarBox.tsx
  apps/desktop-wallet/src/features/switch-wallet/WalletUnlockModal.tsx
  apps/desktop-wallet/src/features/toastMessages/StackedToasts.tsx
  apps/desktop-wallet/src/features/toastMessages/ToastBox.tsx
  apps/desktop-wallet/src/features/toastMessages/ToastMessages.tsx
  apps/desktop-wallet/src/features/toastMessages/ToastMessagesModal.tsx
  apps/desktop-wallet/src/features/toastMessages/toastMessagesActions.ts
  apps/desktop-wallet/src/features/toastMessages/toastMessagesAdapter.ts
  apps/desktop-wallet/src/features/toastMessages/toastMessagesSelectors.ts
  apps/desktop-wallet/src/features/toastMessages/toastMessagesSlice.ts
  apps/desktop-wallet/src/features/toastMessages/toastMessagesTypes.ts
  apps/desktop-wallet/src/features/walletConnect/WalletConnectSessionProposalModal.tsx
  apps/desktop-wallet/src/hooks/useAddressGeneration.tsx
  apps/desktop-wallet/src/modals/NewAddressModal.tsx
  apps/desktop-wallet/src/pages/unlockedWallet/addressesPage/AddressSortingSelect.tsx
  apps/desktop-wallet/src/pages/unlockedWallet/addressesPage/AddressesPageTabContent.tsx
  apps/desktop-wallet/src/pages/unlockedWallet/addressesPage/AddressesTabContent.tsx
  apps/desktop-wallet/src/storage/addresses/addressesActions.ts
  apps/desktop-wallet/src/storage/dApps/dAppActions.ts
  apps/desktop-wallet/src/storage/global/globalActions.ts
  apps/desktop-wallet/src/storage/store.ts
  apps/desktop-wallet/src/storage/transactions/transactionsActions.ts
  apps/desktop-wallet/src/storage/wallets/walletActions.ts
  packages/shared/src/onramp/utils.ts
Labels: 🖥 DW
