Repository alephium/alephium-frontend, pull requests merged in 2025-08, with the labels that each got.

#1454 Update icons
  .changeset/cyan-carrots-find.md
  apps/desktop-wallet/assets/icon.png
  apps/desktop-wallet/public/favicon.ico
  apps/desktop-wallet/public/icons/apple-touch-icon.png
  apps/desktop-wallet/public/icons/logo-192.png
  apps/desktop-wallet/public/icons/logo-32.png
  apps/desktop-wallet/public/icons/logo-48.png
  apps/desktop-wallet/public/icons/logo-512.png
Labels: 🖥 DW

#1465 Groupless fix snap
  .github/workflows/release-desktop.yml
  apps/desktop-wallet/package.json
  pnpm-lock.yaml
Labels: 🖥 DW

#1470 Post groupless
  .changeset/tidy-hairs-buy.md
  apps/desktop-wallet/package.json
  apps/mobile-wallet/src/components/BalanceSummary.tsx
  apps/mobile-wallet/src/components/layout/FlashListScreen.tsx
  apps/mobile-wallet/src/components/layout/FlatListScreen.tsx
  apps/mobile-wallet/src/components/layout/Screen.tsx
  apps/mobile-wallet/src/screens/Dashboard/DashboardScreen.tsx
  apps/mobile-wallet/src/screens/PublicKeysScreen.tsx
  pnpm-lock.yaml
Labels: 📱 MW

#1483 Fix tokens list
  .changeset/fluffy-ends-shine.md
  .changeset/full-cycles-slide.md
  apps/desktop-wallet/package.json
  apps/explorer/package.json
  apps/mobile-wallet/package.json
  packages/shared-react/package.json
  packages/shared-react/src/api/queries/tokenQueries.ts
  packages/shared/package.json
  pnpm-lock.yaml
Labels: 📱 MW, 🖥 DW
