Repository alephium/alephium-frontend, pull requests merged in 2025-07, with the labels that each got.

#1419 Release day
  .changeset/clever-moments-open.md
  .changeset/forty-coats-sink.md
  .changeset/fresh-spies-love.md
  .changeset/lucky-taxis-agree.md
  apps/desktop-wallet/CHANGELOG.md
  apps/desktop-wallet/package.json
  apps/explorer/CHANGELOG.md
  apps/explorer/package.json
  apps/mobile-wallet/CHANGELOG.md
  apps/mobile-wallet/android/app/build.gradle
  apps/mobile-wallet/app.config.js
  apps/mobile-wallet/ios/Alephium/Info.plist
  apps/mobile-wallet/package.json
Labels: 📱 MW, 🖥 DW, 🔎 XPLR

#1416 Create chained txs for any missing funds
  .changeset/every-mammals-lose.md
  .changeset/sweet-trees-see.md
  apps/desktop-wallet/src/features/ledger/utils.ts
  apps/desktop-wallet/src/features/send/sendModal/SendModal.tsx
  apps/desktop-wallet/src/features/send/sendModal/SendModalInfoCheckStep.tsx
  apps/desktop-wallet/src/features/send/sendModal/sendTypes.ts
  apps/desktop-wallet/src/features/walletConnect/SignChainedTxModal.tsx
  apps/desktop-wallet/src/features/walletConnect/WalletConnectSessionRequestEventHandler.tsx
  apps/desktop-wallet/src/hooks/useAddressGeneration.tsx
  apps/desktop-wallet/src/modals/AddressSweepModal.tsx
  apps/desktop-wallet/src/signer.ts
  apps/mobile-wallet/src/components/layout/Surface.tsx
  apps/mobile-wallet/src/contexts/SendContext.tsx
  apps/mobile-wallet/src/contexts/walletConnect/WalletConnectContext.tsx
  apps/mobile-wallet/src/features/ecosystem/dAppMessaging/DappBrowserContext.tsx
  apps/mobile-wallet/src/features/ecosystem/dAppMessaging/dAppMessagingUtils.ts
  apps/mobile-wallet/src/features/ecosystem/modals/SignChainedTxModal.tsx
  apps/mobile-wallet/src/features/send/screens/VerifyScreen.tsx
  packages/shared-react/src/api/apiUtils.ts
  packages/shared/src/types/signTxModalTypes.ts
  packages/shared/src/types/transactions.ts
  packages/shared/src/utils/errors.ts
  packages/shared/src/utils/index.ts
  packages/shared/src/utils/transactions.ts
Labels: WalletConnect, 📱 MW, 🖥 DW

#1438 DW discreet mode fix
  apps/desktop-wallet/locales/en-US/translation.json
  apps/desktop-wallet/src/components/Amount.tsx
Labels: 🖥 DW

#1447 Persist cache improvements
  .changeset/fast-forks-lose.md
  .changeset/stale-hats-drop.md
  apps/desktop-wallet/electron/electron-env.ts
  apps/desktop-wallet/electron/main.ts
  apps/desktop-wallet/electron/menu.ts
  apps/desktop-wallet/electron/preload.ts
  apps/desktop-wallet/src/App.tsx
  apps/desktop-wallet/src/components/Table.tsx
  apps/desktop-wallet/src/features/assetsLists/tokenBalanceRow/AddressTokenBalancesRow.tsx
  apps/desktop-wallet/src/features/assetsLists/tokenBalanceRow/FTAmountCells.tsx
  apps/desktop-wallet/src/features/assetsLists/tokenBalanceRow/FTWorthCell.tsx
  apps/desktop-wallet/src/features/assetsLists/tokenBalanceRow/TokenBalancesRow.tsx
  apps/desktop-wallet/src/features/ledger/useInitializeAppWithLedgerData.tsx
  apps/desktop-wallet/src/features/transactionsDisplay/transactionLists/lists/WalletTransactionsList.tsx
  apps/desktop-wallet/src/hooks/useWalletLock.ts
  apps/desktop-wallet/src/index.tsx
  apps/desktop-wallet/src/modals/AppModals.tsx
  apps/desktop-wallet/src/modals/WalletRemovalModal.tsx
  apps/desktop-wallet/src/pages/NewWallet/CreateWalletPage.tsx
  apps/desktop-wallet/src/pages/unlockedWallet/activityPage/ActivityPage.tsx
  apps/desktop-wallet/src/pages/unlockedWallet/addressesPage/addressListRow/AddressListRow.tsx
  apps/desktop-wallet/src/routes/UnlockedWalletRoutes.tsx
  apps/desktop-wallet/src/storage/tanstackQueryCache/tanstackIndexedDBPersister.ts
  apps/desktop-wallet/src/storage/tanstackQueryCache/useClearQueryCacheOnWalletLock.ts
  apps/desktop-wallet/src/storage/tanstackQueryCache/usePersistQueryCacheBeforeQuit.ts
  apps/mobile-wallet/ios/Podfile.lock
  apps/mobile-wallet/src/App.tsx
  apps/mobile-wallet/src/features/persistQueryCache/usePersistQueryCacheOnBackground.ts
  packages/shared-react/src/api/persistQueryClientContext.tsx
  packages/shared-react/src/api/queries/transactionQueries.ts
  packages/shared/test/fixtures/transactions.json
  packages/shared/test/transactions-test.ts
Labels: 📱 MW, 🖥 DW
